epm-play: print fatal error if there is error during install

diff --git a/bin/epm-play b/bin/epm-play
--- a/bin/epm-play
+++ b/bin/epm-play
@@ -117,5 +117,5 @@ if [ "$1" = "--list-all" ] || [ -z "$*" ] ; then
 fi
 
 #__check_installed_app "$1" && info "$1 is already installed (use --remove to remove)" && exit 1
-__epm_play_run "$1" --run && __save_installed_app "$1"
+__epm_play_run "$1" --run && __save_installed_app "$1" || fatal "There was some error during install the application."
 }
