epm-release_upgrade: don't touch apt-conf and alt-release during update to p10

diff --git a/bin/epm-release_upgrade b/bin/epm-release_upgrade
--- a/bin/epm-release_upgrade
+++ b/bin/epm-release_upgrade
@@ -145,8 +145,10 @@ get_fix_release_pkg()
 	if [ "$TO" = "Sisyphus" ] ; then
 		TO="sisyphus"
 		echo "apt-conf-$TO"
+	elif [ "$TO" = "p10" ] ; then
+		true
+		#echo "apt-conf-$TO"
 	else
-# will it update /etc/altlinux-release
 		echo "apt-conf-branch"
 	fi
 
@@ -335,7 +337,7 @@ __switch_alt_to_distro()
 			echo '%_priority_distbranch p10' >/etc/rpm/macros.d/p10
 			__epm_ru_update || fatal
 			docmd epm upgrade || fatal "Check an error and run epm release-upgrade again"
-			docmd epm install rpm apt "$(get_fix_release_pkg --force "$TO")" || fatal "Check an error and run epm release-upgrade again"
+			docmd epm install rpm apt "$(get_fix_release_pkg "$TO")" || fatal "Check an error and run epm release-upgrade again"
 			__check_system
 			docmd epm update-kernel -t std-def || fatal
 			;;
