epm full-upgrade: add --ipfs support for epm play

diff --git a/bin/epm-full_upgrade b/bin/epm-full_upgrade
--- a/bin/epm-full_upgrade
+++ b/bin/epm-full_upgrade
@@ -42,6 +42,9 @@ epm_full_upgrade()
                 ;;
             "--interactive")           # HELPCMD: ask before every step
                 ;;
+            "--ipfs")                  # HELPCMD: use IPFS for epm play
+                ipfs='--ipfs'
+                ;;
             "--no-epm-play")           # HELPCMD: skip epm play during full upgrade
                 full_upgrade_no_epm_play=1
                 ;;
@@ -105,9 +108,9 @@ confirm_action()
     if [ -z "$full_upgrade_no_epm_play" ] ; then
         [ -n "$quiet" ] || echo
         if [ -n "$force" ] ; then
-            docmd epm $dryrun play #|| fatal "updating of applications installed via epm play is failed."
+            docmd epm $dryrun play $ipfs --force #|| fatal "updating of applications installed via epm play is failed."
         else
-            docmd epm $dryrun play --update all #|| fatal "updating of applications installed via epm play is failed."
+            docmd epm $dryrun play $ipfs --update all #|| fatal "updating of applications installed via epm play is failed."
         fi
     fi
 
