epm: replace tab with 4 spaces

diff --git a/bin/epm-autoremove b/bin/epm-autoremove
--- a/bin/epm-autoremove
+++ b/bin/epm-autoremove
@@ -21,126 +21,126 @@ load_helper epm-check_updated_repo
 
 __epm_print_excluded()
 {
-	local pkgs="$1"
-	local fullpkgs="$2"
-	local excluded
-	excluded="$(estrlist exclude "$pkgs" "$fullpkgs")"
-	if [ -n "$excluded" ] ; then
-		echo "Skipped manually installed:"
-		estrlist union $excluded
-	fi
+    local pkgs="$1"
+    local fullpkgs="$2"
+    local excluded
+    excluded="$(estrlist exclude "$pkgs" "$fullpkgs")"
+    if [ -n "$excluded" ] ; then
+        echo "Skipped manually installed:"
+        estrlist union $excluded
+    fi
 }
 
 __epm_autoremove_altrpm_pp()
 {
-	local pkgs fullpkgs
+    local pkgs fullpkgs
 
-	info "Removing unused python/perl modules..."
+    info "Removing unused python/perl modules..."
 
-	local libexclude="$1"
+    local libexclude="$1"
 
-	local flag=
+    local flag=
 
-	showcmd "apt-cache list-nodeps | grep -E -- \"$libexclude\""
-	fullpkgs=$(apt-cache list-nodeps | grep -E -- "$libexclude" )
-	pkgs=$(skip_manually_installed $fullpkgs)
+    showcmd "apt-cache list-nodeps | grep -E -- \"$libexclude\""
+    fullpkgs=$(apt-cache list-nodeps | grep -E -- "$libexclude" )
+    pkgs=$(skip_manually_installed $fullpkgs)
 
-	if [ -n "$dryrun" ] ; then
-		info "Packages for autoremoving:"
-		echo "$pkgs"
-		__epm_print_excluded "$pkgs" "$fullpkgs"
-		return 0
-	fi
+    if [ -n "$dryrun" ] ; then
+        info "Packages for autoremoving:"
+        echo "$pkgs"
+        __epm_print_excluded "$pkgs" "$fullpkgs"
+        return 0
+    fi
 
-	if [ -n "$pkgs" ] ; then
-		info "The command we will run:"
-		showcmd rpm -v -e $pkgs
-		__epm_print_excluded "$pkgs" "$fullpkgs"
+    if [ -n "$pkgs" ] ; then
+        info "The command we will run:"
+        showcmd rpm -v -e $pkgs
+        __epm_print_excluded "$pkgs" "$fullpkgs"
 
-		confirm_info "We will remove unused (without dependencies) packages above."
+        confirm_info "We will remove unused (without dependencies) packages above."
 
-		sudocmd rpm -v -e $pkgs && flag=1
-	fi
+        sudocmd rpm -v -e $pkgs && flag=1
+    fi
 
 
-	if [ -n "$flag" ] ; then
-		info ""
-		info "call again for next cycle until all modules will be removed"
-		__epm_autoremove_altrpm_pp "$libexclude"
-	fi
+    if [ -n "$flag" ] ; then
+        info ""
+        info "call again for next cycle until all modules will be removed"
+        __epm_autoremove_altrpm_pp "$libexclude"
+    fi
 
-	return 0
+    return 0
 }
 
 __epm_autoremove_altrpm_package_group()
 {
-	if epmqp "$*" ; then
-		confirm_info "We will remove unused (without dependencies) packages above."
-		docmd epm remove $(epmqp --short "$*")
-	fi
+    if epmqp "$*" ; then
+        confirm_info "We will remove unused (without dependencies) packages above."
+        docmd epm remove $(epmqp --short "$*")
+    fi
 }
 
 __epm_autoremove_altrpm_lib()
 {
-	local pkgs fullpkgs
+    local pkgs fullpkgs
 
-	local flag=''
-	local opt="$1"
-	local libgrep=''
-	info
-	case "$opt" in
-		libs)
-			info "Removing all non -devel/-debuginfo libs packages not need by anything..."
-			local develrule='-(devel|devel-static)$'
-			libgrep='^(lib|bzlib|zlib)'
-			;;
-		i586-libs)
-			info "Removing all non -devel/-debuginfo i586-libs packages not need by anything..."
-			local develrule='-(devel|devel-static)$'
-			libgrep='^(i586-lib|i586-bzlib|i586-zlib)'
-			;;
-		devel)
-			info "Removing all non -debuginfo libs packages (-devel too) not need by anything..."
-			local develrule='-(NONONO)$'
-			libgrep='^(lib|bzlib|zlib)'
-			;;
-		*)
-			fatal "Internal error: unsupported opt $opt"
-	esac
+    local flag=''
+    local opt="$1"
+    local libgrep=''
+    info
+    case "$opt" in
+        libs)
+            info "Removing all non -devel/-debuginfo libs packages not need by anything..."
+            local develrule='-(devel|devel-static)$'
+            libgrep='^(lib|bzlib|zlib)'
+            ;;
+        i586-libs)
+            info "Removing all non -devel/-debuginfo i586-libs packages not need by anything..."
+            local develrule='-(devel|devel-static)$'
+            libgrep='^(i586-lib|i586-bzlib|i586-zlib)'
+            ;;
+        devel)
+            info "Removing all non -debuginfo libs packages (-devel too) not need by anything..."
+            local develrule='-(NONONO)$'
+            libgrep='^(lib|bzlib|zlib)'
+            ;;
+        *)
+            fatal "Internal error: unsupported opt $opt"
+    esac
 
-	# https://www.altlinux.org/APT_в_ALT_Linux/Советы_по_использованию#apt-cache_list-nodeps
-	showcmd "apt-cache list-nodeps | grep -E -- \"$libgrep\""
-	fullpkgs=$(apt-cache list-nodeps | grep -E -- "$libgrep" \
-		| sed -e "s/[-\.]32bit$//g" \
-		| grep -E -v -- "$develrule" \
-		| grep -E -v -- "-(debuginfo)$" \
-		| grep -E -v -- "-(util|utils|tool|tools|plugin|daemon|help)$" \
-		| grep -E -v -- "^(libsystemd|libreoffice|libnss|libvirt-client|libvirt-daemon|libsasl2-plugin|eepm|distro_info)" )
-	pkgs=$(skip_manually_installed $fullpkgs)
+    # https://www.altlinux.org/APT_в_ALT_Linux/Советы_по_использованию#apt-cache_list-nodeps
+    showcmd "apt-cache list-nodeps | grep -E -- \"$libgrep\""
+    fullpkgs=$(apt-cache list-nodeps | grep -E -- "$libgrep" \
+        | sed -e "s/[-\.]32bit$//g" \
+        | grep -E -v -- "$develrule" \
+        | grep -E -v -- "-(debuginfo)$" \
+        | grep -E -v -- "-(util|utils|tool|tools|plugin|daemon|help)$" \
+        | grep -E -v -- "^(libsystemd|libreoffice|libnss|libvirt-client|libvirt-daemon|libsasl2-plugin|eepm|distro_info)" )
+    pkgs=$(skip_manually_installed $fullpkgs)
 
-	if [ -n "$dryrun" ] ; then
-		info "Packages for autoremoving:"
-		echo "$pkgs"
-		__epm_print_excluded "$pkgs" "$fullpkgs"
-		return 0
-	fi
+    if [ -n "$dryrun" ] ; then
+        info "Packages for autoremoving:"
+        echo "$pkgs"
+        __epm_print_excluded "$pkgs" "$fullpkgs"
+        return 0
+    fi
 
-	if [ -n "$pkgs" ] ; then
-		info "The command we will run:"
-		showcmd rpm -v -e $pkgs
-		__epm_print_excluded "$pkgs" "$fullpkgs"
-		confirm_info "We will remove unused (without dependencies) packages above."
+    if [ -n "$pkgs" ] ; then
+        info "The command we will run:"
+        showcmd rpm -v -e $pkgs
+        __epm_print_excluded "$pkgs" "$fullpkgs"
+        confirm_info "We will remove unused (without dependencies) packages above."
 
-		sudocmd rpm -v -e $pkgs && flag=1
-	fi
+        sudocmd rpm -v -e $pkgs && flag=1
+    fi
 
-	if [ -n "$flag" ] ; then
-		info ""
-		info "call again for next cycle until all libs will be removed"
-		__epm_autoremove_altrpm_lib $opt
-	fi
+    if [ -n "$flag" ] ; then
+        info ""
+        info "call again for next cycle until all libs will be removed"
+        __epm_autoremove_altrpm_lib $opt
+    fi
 
-	return 0
+    return 0
 }
 
 
@@ -148,67 +148,67 @@ epm_autoremove_default_groups="python2 python3 perl gem ruby libs"
 
 __epm_autoremove_altrpm()
 {
-	local i
-	load_helper epm-packages
-	assure_exists /usr/share/apt/scripts/list-nodeps.lua apt-scripts
+    local i
+    load_helper epm-packages
+    assure_exists /usr/share/apt/scripts/list-nodeps.lua apt-scripts
 
-	if [ -z "$pkg_names" ] ; then
-		pkg_names="$epm_autoremove_default_groups"
-	elif [ "$pkg_names" = "python" ] ; then
-		pkg_names="python2 python3"
-	fi
+    if [ -z "$pkg_names" ] ; then
+        pkg_names="$epm_autoremove_default_groups"
+    elif [ "$pkg_names" = "python" ] ; then
+        pkg_names="python2 python3"
+    fi
 
-	for i in $pkg_names ; do
-		case $i in
-		libs)
-			__epm_autoremove_altrpm_lib libs
-			;;
-		i586-libs)
-			__epm_autoremove_altrpm_lib i586-libs
-			;;
-		debuginfo)
-			__epm_autoremove_altrpm_package_group '-debuginfo-'
-			;;
-		devel)
-			__epm_autoremove_altrpm_package_group '^(rpm-build-|gcc-|glibc-devel-)'
-			;;
-		python2)
-			__epm_autoremove_altrpm_pp '^(python-module-|python-modules-)'
-			;;
-		python3)
-			__epm_autoremove_altrpm_pp '^(python3-module-|python3-modules-)'
-			;;
-		php)
-			__epm_autoremove_altrpm_pp '^(php7-|php5-|php8-)'
-			;;
-		gem)
-			__epm_autoremove_altrpm_pp '^(gem-)'
-			;;
-		ruby)
-			__epm_autoremove_altrpm_pp '^(ruby-)'
-			;;
-		perl)
-			__epm_autoremove_altrpm_pp '^(perl-)'
-			;;
-		libs-devel)
-			__epm_autoremove_altrpm_lib devel
-			;;
-		*)
-			fatal "autoremove: unsupported '$i'. Use epm autoremove --help to list supported ones"
-			;;
-		esac
-	done
+    for i in $pkg_names ; do
+        case $i in
+        libs)
+            __epm_autoremove_altrpm_lib libs
+            ;;
+        i586-libs)
+            __epm_autoremove_altrpm_lib i586-libs
+            ;;
+        debuginfo)
+            __epm_autoremove_altrpm_package_group '-debuginfo-'
+            ;;
+        devel)
+            __epm_autoremove_altrpm_package_group '^(rpm-build-|gcc-|glibc-devel-)'
+            ;;
+        python2)
+            __epm_autoremove_altrpm_pp '^(python-module-|python-modules-)'
+            ;;
+        python3)
+            __epm_autoremove_altrpm_pp '^(python3-module-|python3-modules-)'
+            ;;
+        php)
+            __epm_autoremove_altrpm_pp '^(php7-|php5-|php8-)'
+            ;;
+        gem)
+            __epm_autoremove_altrpm_pp '^(gem-)'
+            ;;
+        ruby)
+            __epm_autoremove_altrpm_pp '^(ruby-)'
+            ;;
+        perl)
+            __epm_autoremove_altrpm_pp '^(perl-)'
+            ;;
+        libs-devel)
+            __epm_autoremove_altrpm_lib devel
+            ;;
+        *)
+            fatal "autoremove: unsupported '$i'. Use epm autoremove --help to list supported ones"
+            ;;
+        esac
+    done
 
-	return 0
+    return 0
 }
 
 epm_autoremove_print_help()
 {
-	echo "epm autoremove removes unneeded packages from the system"
-	echo "run 'epm autoremove' to use apt-get autoremove"
-	echo "or run 'epm autoremove --direct [group1] [group2] ...' to use epm implementation"
-	echo "Default groups: $epm_autoremove_default_groups"
-	cat <<EOF
+    echo "epm autoremove removes unneeded packages from the system"
+    echo "run 'epm autoremove' to use apt-get autoremove"
+    echo "or run 'epm autoremove --direct [group1] [group2] ...' to use epm implementation"
+    echo "Default groups: $epm_autoremove_default_groups"
+    cat <<EOF
 Supported package groups:
     libs       - unused libraries
     libs-devel - unused -devel packages
@@ -233,125 +233,125 @@ epm_autoremove()
 {
 
 case $BASEDISTRNAME in
-	"alt")
-		if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "help" ] ; then
-			epm_autoremove_print_help
-			return 0
-		fi
+    "alt")
+        if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "help" ] ; then
+            epm_autoremove_print_help
+            return 0
+        fi
 
-		if [ -z "$direct" ] ; then
-			[ -n "$1" ] && fatal "Run autoremove without args or with --direct. Check epm autoremove --help to available commands."
-			sudocmd apt-get $(subst_option non_interactive -y) autoremove $dryrun
-			local RET=$?
-			if [ "$RET" != 0 ] ; then
-				echo
-				info "Also you can run 'epm autoremove --direct' to use epm implementation of autoremove (see --help)"
-				return
-			fi
-		else
-			__epm_autoremove_altrpm "$@"
-		fi
+        if [ -z "$direct" ] ; then
+            [ -n "$1" ] && fatal "Run autoremove without args or with --direct. Check epm autoremove --help to available commands."
+            sudocmd apt-get $(subst_option non_interactive -y) autoremove $dryrun
+            local RET=$?
+            if [ "$RET" != 0 ] ; then
+                echo
+                info "Also you can run 'epm autoremove --direct' to use epm implementation of autoremove (see --help)"
+                return
+            fi
+        else
+            __epm_autoremove_altrpm "$@"
+        fi
 
-		#[ -n "$dryrun" ] && return
+        #[ -n "$dryrun" ] && return
 
-		# remove old kernels only by a default way
-		[ -n "$1" ] && return
+        # remove old kernels only by a default way
+        [ -n "$1" ] && return
 
-		docmd epm remove-old-kernels $dryrun
+        docmd epm remove-old-kernels $dryrun
 
-		if [ -z "$direct" ] ; then
-			echo
-			info "Also you can run 'epm autoremove --direct' to use epm implementation of autoremove (see --help)"
-		fi
+        if [ -z "$direct" ] ; then
+            echo
+            info "Also you can run 'epm autoremove --direct' to use epm implementation of autoremove (see --help)"
+        fi
 
-		return
-		;;
-	*)
-		;;
+        return
+        ;;
+    *)
+        ;;
 esac
 
 [ -z "$pkg_filenames" ] || fatal "No arguments are allowed here"
 
 case $PMTYPE in
-	apt-dpkg|aptitude-dpkg)
-		sudocmd apt-get autoremove $(subst_option non_interactive -y) $dryrun
-		;;
-	aura)
-		if [ -n "$dryrun" ] ; then
-			fatal "--dry-run is not supported yet"
-		fi
-		sudocmd aura -Oj
-		;;
-	packagekit)
-		docmd pkcon repair --autoremove
-		;;
-	yum-rpm)
-		# cleanup orphanes?
-		while true ; do
-			# shellcheck disable=SC2046
-			docmd package-cleanup --leaves $(subst_option non_interactive --assumeyes)
-			# FIXME: package-cleanup have to use stderr for errors
-			local PKGLIST=$(package-cleanup -q --leaves | grep -v "^eepm-")
-			[ -n "$PKGLIST" ] || break
-			docmd epm remove $PKGLIST
-		done
-		;;
-	dnf-rpm)
-		if [ -n "$dryrun" ] ; then
-			fatal "--dry-run is not supported yet"
-		fi
-		sudocmd dnf autoremove
-		;;
-	# see autoorhans
-	#urpm-rpm)
-	#	sudocmd urpme --auto-orphans
-	#	;;
-	emerge)
-		if [ -n "$dryrun" ] ; then
-			fatal "--dry-run is not supported yet"
-		fi
-		sudocmd emerge --depclean
-		assure_exists revdep-rebuild
-		sudocmd revdep-rebuild
-		;;
-	# see autoorhans
-	#pacman)
-	#	sudocmd pacman -Qdtq | sudocmd pacman -Rs -
-	#	;;
-	slackpkg)
-		# clean-system removes non official packages
-		#sudocmd slackpkg clean-system
-		;;
-	guix)
-		sudocmd guix gc
-		;;
-	pkgng)
-		sudocmd pkg autoremove
-		;;
-	zypper-rpm)
-		# https://www.linux.org.ru/forum/desktop/11931830
-		assure_exists zypper zypper 1.9.3
-		sudocmd zypper packages --unneeded
-		# FIXME: x86_64/i586 are duplicated
-		local PKGLIST=$(zypper packages --unneeded | tail -n +5 | cut -d \| -f 3 | sort -u)
-		showcmd epm remove --clean-deps $PKGLIST
-		;;
-	xbps)
-		if [ -n "$dryrun" ] ; then
-			fatal "--dry-run is not supported yet"
-		fi
-		sudocmd xbps-remove -O
-		;;
-	opkg)
-		if [ -n "$dryrun" ] ; then
-			sudocmd opkg --noaction --autoremove
-		else
-			sudocmd opkg --autoremove
-		fi
-		;;
-	*)
-		fatal "Have no suitable command for $PMTYPE"
-		;;
+    apt-dpkg|aptitude-dpkg)
+        sudocmd apt-get autoremove $(subst_option non_interactive -y) $dryrun
+        ;;
+    aura)
+        if [ -n "$dryrun" ] ; then
+            fatal "--dry-run is not supported yet"
+        fi
+        sudocmd aura -Oj
+        ;;
+    packagekit)
+        docmd pkcon repair --autoremove
+        ;;
+    yum-rpm)
+        # cleanup orphanes?
+        while true ; do
+            # shellcheck disable=SC2046
+            docmd package-cleanup --leaves $(subst_option non_interactive --assumeyes)
+            # FIXME: package-cleanup have to use stderr for errors
+            local PKGLIST=$(package-cleanup -q --leaves | grep -v "^eepm-")
+            [ -n "$PKGLIST" ] || break
+            docmd epm remove $PKGLIST
+        done
+        ;;
+    dnf-rpm)
+        if [ -n "$dryrun" ] ; then
+            fatal "--dry-run is not supported yet"
+        fi
+        sudocmd dnf autoremove
+        ;;
+    # see autoorhans
+    #urpm-rpm)
+    #    sudocmd urpme --auto-orphans
+    #    ;;
+    emerge)
+        if [ -n "$dryrun" ] ; then
+            fatal "--dry-run is not supported yet"
+        fi
+        sudocmd emerge --depclean
+        assure_exists revdep-rebuild
+        sudocmd revdep-rebuild
+        ;;
+    # see autoorhans
+    #pacman)
+    #    sudocmd pacman -Qdtq | sudocmd pacman -Rs -
+    #    ;;
+    slackpkg)
+        # clean-system removes non official packages
+        #sudocmd slackpkg clean-system
+        ;;
+    guix)
+        sudocmd guix gc
+        ;;
+    pkgng)
+        sudocmd pkg autoremove
+        ;;
+    zypper-rpm)
+        # https://www.linux.org.ru/forum/desktop/11931830
+        assure_exists zypper zypper 1.9.3
+        sudocmd zypper packages --unneeded
+        # FIXME: x86_64/i586 are duplicated
+        local PKGLIST=$(zypper packages --unneeded | tail -n +5 | cut -d \| -f 3 | sort -u)
+        showcmd epm remove --clean-deps $PKGLIST
+        ;;
+    xbps)
+        if [ -n "$dryrun" ] ; then
+            fatal "--dry-run is not supported yet"
+        fi
+        sudocmd xbps-remove -O
+        ;;
+    opkg)
+        if [ -n "$dryrun" ] ; then
+            sudocmd opkg --noaction --autoremove
+        else
+            sudocmd opkg --autoremove
+        fi
+        ;;
+    *)
+        fatal "Have no suitable command for $PMTYPE"
+        ;;
 esac
 
 }
diff --git a/bin/epm-changelog b/bin/epm-changelog
--- a/bin/epm-changelog
+++ b/bin/epm-changelog
@@ -21,101 +21,101 @@ load_helper epm-query
 
 __epm_changelog_apt()
 {
-	local i
-	for i in $@ ; do
-		docmd apt-cache show $i | grep -A 1000 "^Changelog:"
-	done
+    local i
+    for i in $@ ; do
+        docmd apt-cache show $i | grep -A 1000 "^Changelog:"
+    done
 }
 
 __epm_changelog_files()
 {
-	[ -z "$*" ] && return
+    [ -z "$*" ] && return
 
-	# TODO: detect every file
-	case $(get_package_type $1) in
-		rpm)
-			assure_exists rpm
-			docmd_foreach "rpm -q -p --changelog" $@
-			;;
-#		deb)
-#			
-#			;;
-		*)
-			fatal "Have no suitable command for $1"
-			;;
-	esac
+    # TODO: detect every file
+    case $(get_package_type $1) in
+        rpm)
+            assure_exists rpm
+            docmd_foreach "rpm -q -p --changelog" $@
+            ;;
+#        deb)
+#            
+#            ;;
+        *)
+            fatal "Have no suitable command for $1"
+            ;;
+    esac
 }
 
 __epm_changelog_local_names()
 {
-	[ -z "$*" ] && return
+    [ -z "$*" ] && return
 
-	case $PMTYPE in
-		apt-rpm|yum-rpm|dnf-rpm|urpm-rpm|zypper-rpm)
-			docmd_foreach "rpm -q --changelog" $@
-			;;
-		apt-dpkg|aptitude-dpkg)
-			docmd zcat /usr/share/doc/$1/changelog.Debian.gz
-			;;
-		emerge)
-			assure_exists equery
-			docmd equery changes -f $1
-			;;
-		pacman)
-			docmd pacman -Qc $1
-			;;
-		*)
-			fatal "Have no suitable command for $PMTYPE"
-			;;
-	esac
+    case $PMTYPE in
+        apt-rpm|yum-rpm|dnf-rpm|urpm-rpm|zypper-rpm)
+            docmd_foreach "rpm -q --changelog" $@
+            ;;
+        apt-dpkg|aptitude-dpkg)
+            docmd zcat /usr/share/doc/$1/changelog.Debian.gz
+            ;;
+        emerge)
+            assure_exists equery
+            docmd equery changes -f $1
+            ;;
+        pacman)
+            docmd pacman -Qc $1
+            ;;
+        *)
+            fatal "Have no suitable command for $PMTYPE"
+            ;;
+    esac
 }
 
 __epm_changelog_unlocal_names()
 {
-	[ -z "$*" ] && return
+    [ -z "$*" ] && return
 
-	case $PMTYPE in
-		apt-rpm)
-			__epm_changelog_apt "$1"
-			;;
-		#apt-dpkg)
-		#	# FIXME: only first pkg
-		#	docmd zcat /usr/share/doc/$1/changelog.Debian.gz | less
-		#	;;
-		#yum-rpm)
-		#	sudocmd yum clean all
-		#	;;
-		urpm-rpm)
-			docmd urpmq --changelog "$1"
-			;;
-		#zypper-rpm)
-		#	sudocmd zypper clean
-		#	;;
-		emerge)
-			assure_exists equery
-			docmd equery changes -f "$1"
-			;;
-		*)
-			fatal "Have no suitable command for $PMTYPE. Try install the package firstly."
-			;;
-	esac
+    case $PMTYPE in
+        apt-rpm)
+            __epm_changelog_apt "$1"
+            ;;
+        #apt-dpkg)
+        #    # FIXME: only first pkg
+        #    docmd zcat /usr/share/doc/$1/changelog.Debian.gz | less
+        #    ;;
+        #yum-rpm)
+        #    sudocmd yum clean all
+        #    ;;
+        urpm-rpm)
+            docmd urpmq --changelog "$1"
+            ;;
+        #zypper-rpm)
+        #    sudocmd zypper clean
+        #    ;;
+        emerge)
+            assure_exists equery
+            docmd equery changes -f "$1"
+            ;;
+        *)
+            fatal "Have no suitable command for $PMTYPE. Try install the package firstly."
+            ;;
+    esac
 
 }
 
 
 epm_changelog()
 {
-	[ -n "$pkg_filenames" ] || fatal "Changelog: Missing package(s) name"
+    [ -n "$pkg_filenames" ] || fatal "Changelog: Missing package(s) name"
 
-	__epm_changelog_files $pkg_files
+    __epm_changelog_files $pkg_files
 
-	# TODO: add less or bat
-	local pkg
-	for pkg in $pkg_names ; do
-		if is_installed $pkg ; then
-			__epm_changelog_local_names $pkg
-		else
-			__epm_changelog_unlocal_names $pkg
-		fi
-	done
+    # TODO: add less or bat
+    local pkg
+    for pkg in $pkg_names ; do
+        if is_installed $pkg ; then
+            __epm_changelog_local_names $pkg
+        else
+            __epm_changelog_unlocal_names $pkg
+        fi
+    done
 }
diff --git a/bin/epm-check b/bin/epm-check
--- a/bin/epm-check
+++ b/bin/epm-check
@@ -25,60 +25,60 @@ update_repo_if_needed
 local APTOPTIONS="$(subst_option non_interactive -y)"
 local DNFOPTIONS="$(subst_option non_interactive -y) $(subst_option verbose --verbose) "
 case $PMTYPE in
-	apt-rpm)
-		#sudocmd apt-get check || exit
-		#sudocmd apt-get update || exit
-		sudocmd apt-get -f $APTOPTIONS install || return
-		info "You can use epm dedup also"
-		;;
-	apt-dpkg)
-		#sudocmd apt-get check || exit
-		#sudocmd apt-get update || exit
-		sudocmd apt-get -f $APTOPTIONS install || return
-		;;
-	packagekit)
-		docmd pkcon repair
-		;;
-	aptitude-dpkg)
-		sudocmd aptitude -f $APTOPTIONS install || return
-		#sudocmd apt-get autoremove
-		;;
-	yum-rpm)
-		docmd yum check $DNFOPTIONS
-		docmd package-cleanup --problems
+    apt-rpm)
+        #sudocmd apt-get check || exit
+        #sudocmd apt-get update || exit
+        sudocmd apt-get -f $APTOPTIONS install || return
+        info "You can use epm dedup also"
+        ;;
+    apt-dpkg)
+        #sudocmd apt-get check || exit
+        #sudocmd apt-get update || exit
+        sudocmd apt-get -f $APTOPTIONS install || return
+        ;;
+    packagekit)
+        docmd pkcon repair
+        ;;
+    aptitude-dpkg)
+        sudocmd aptitude -f $APTOPTIONS install || return
+        #sudocmd apt-get autoremove
+        ;;
+    yum-rpm)
+        docmd yum check $DNFOPTIONS
+        docmd package-cleanup --problems
 
-		#docmd package-cleanup --dupes
-		sudocmd package-cleanup --cleandupes
+        #docmd package-cleanup --dupes
+        sudocmd package-cleanup --cleandupes
 
-		docmd rpm -Va --nofiles --nodigest
-		;;
-	dnf-rpm)
-		sudocmd dnf check $DNFOPTIONS
-		;;
-	emerge)
-		sudocmd revdep-rebuild
-		;;
-	#urpm-rpm)
-	#	sudocmd urpme --auto-orphans
-	#	;;
-	zypper-rpm)
-		sudocmd zypper $(subst_option non_interactive --non-interactive) verify
-		;;
-	conary)
-		sudocmd conary verify
-		;;
-	pkgng)
-		sudocmd pkg check -d -a
-		;;
-	homebrew)
-		docmd brew doctor
-		;;
-	xbps)
-		sudocmd xbps-pkgdb -a
-		;;
-	*)
-		fatal "Have no suitable command for $PMTYPE"
-		;;
+        docmd rpm -Va --nofiles --nodigest
+        ;;
+    dnf-rpm)
+        sudocmd dnf check $DNFOPTIONS
+        ;;
+    emerge)
+        sudocmd revdep-rebuild
+        ;;
+    #urpm-rpm)
+    #    sudocmd urpme --auto-orphans
+    #    ;;
+    zypper-rpm)
+        sudocmd zypper $(subst_option non_interactive --non-interactive) verify
+        ;;
+    conary)
+        sudocmd conary verify
+        ;;
+    pkgng)
+        sudocmd pkg check -d -a
+        ;;
+    homebrew)
+        docmd brew doctor
+        ;;
+    xbps)
+        sudocmd xbps-pkgdb -a
+        ;;
+    *)
+        fatal "Have no suitable command for $PMTYPE"
+        ;;
 esac
 
 }
diff --git a/bin/epm-conflicts b/bin/epm-conflicts
--- a/bin/epm-conflicts
+++ b/bin/epm-conflicts
@@ -21,75 +21,75 @@ load_helper epm-query
 
 epm_conflicts_files()
 {
-	[ -n "$pkg_files" ] || return
+    [ -n "$pkg_files" ] || return
 
-	case $(get_package_type $pkg_files) in
-		rpm)
-			assure_exists rpm
-			docmd rpm -q --conflicts -p $pkg_files
-			;;
-		#deb)
-		#	a= docmd dpkg -I $pkg_files | grep "^ *Depends:" | sed "s|^ *Depends:||g"
-		#	;;
-		*)
-			fatal "Have no suitable command for $PMTYPE"
-			;;
-	esac
+    case $(get_package_type $pkg_files) in
+        rpm)
+            assure_exists rpm
+            docmd rpm -q --conflicts -p $pkg_files
+            ;;
+        #deb)
+        #    a= docmd dpkg -I $pkg_files | grep "^ *Depends:" | sed "s|^ *Depends:||g"
+        #    ;;
+        *)
+            fatal "Have no suitable command for $PMTYPE"
+            ;;
+    esac
 }
 
 epm_conflicts_names()
 {
-	local CMD
-	[ -n "$pkg_names" ] || return
+    local CMD
+    [ -n "$pkg_names" ] || return
 
 # by package name
 case $PMTYPE in
-	apt-rpm)
-		# FIXME: need fix for a few names case
-		# FIXME: too low level of requires name (libSOME.so)
-		if is_installed $pkg_names ; then
-			CMD="rpm -q --conflicts"
-		else
-			EXTRA_SHOWDOCMD=' | grep "Conflicts:"'
-			docmd apt-cache show $pkg_names | grep "Conflicts:"
-			return
-		fi
+    apt-rpm)
+        # FIXME: need fix for a few names case
+        # FIXME: too low level of requires name (libSOME.so)
+        if is_installed $pkg_names ; then
+            CMD="rpm -q --conflicts"
+        else
+            EXTRA_SHOWDOCMD=' | grep "Conflicts:"'
+            docmd apt-cache show $pkg_names | grep "Conflicts:"
+            return
+        fi
 
-		;;
-	urpm-rpm|zypper-rpm)
-		# FIXME: use hi level commands
-		CMD="rpm -q --conflicts"
-		;;
-	#yum-rpm)
-	#	CMD="yum deplist"
-	#	;;
-	#pacman)
-	#	CMD="pactree"
-	#	;;
-	apt-dpkg)
-		# FIXME: need fix for a few names case
-		if is_installed $pkg_names ; then
-			showcmd dpkg -s $pkg_names
-			a='' dpkg -s $pkg_names | grep "^Conflicts:" | sed "s|^Conflicts:||g"
-			return
-		else
-			EXTRA_SHOWDOCMD=' | grep "Conflicts:"'
-			docmd apt-cache show $pkg_names | grep "Conflicts:"
-			return
-		fi
-		;;
-	# TODO: why-not show who conflicts with us
-	#aptitude-dpkg)
-	#	docmd aptitude why-not $pkg_names
-	#	;;
+        ;;
+    urpm-rpm|zypper-rpm)
+        # FIXME: use hi level commands
+        CMD="rpm -q --conflicts"
+        ;;
+    #yum-rpm)
+    #    CMD="yum deplist"
+    #    ;;
+    #pacman)
+    #    CMD="pactree"
+    #    ;;
+    apt-dpkg)
+        # FIXME: need fix for a few names case
+        if is_installed $pkg_names ; then
+            showcmd dpkg -s $pkg_names
+            a='' dpkg -s $pkg_names | grep "^Conflicts:" | sed "s|^Conflicts:||g"
+            return
+        else
+            EXTRA_SHOWDOCMD=' | grep "Conflicts:"'
+            docmd apt-cache show $pkg_names | grep "Conflicts:"
+            return
+        fi
+        ;;
+    # TODO: why-not show who conflicts with us
+    #aptitude-dpkg)
+    #    docmd aptitude why-not $pkg_names
+    #    ;;
 
-	#emerge)
-	#	assure_exists equery
-	#	CMD="equery depgraph"
-	#	;;
-	*)
-		fatal "Have no suitable command for $PMTYPE"
-		;;
+    #emerge)
+    #    assure_exists equery
+    #    CMD="equery depgraph"
+    #    ;;
+    *)
+        fatal "Have no suitable command for $PMTYPE"
+        ;;
 esac
 
 
@@ -99,7 +99,7 @@ docmd $CMD $pkg_names
 
 epm_conflicts()
 {
-	[ -n "$pkg_filenames" ] || fatal "Conflicts: Missing package(s) name"
-	epm_conflicts_files
-	epm_conflicts_names
+    [ -n "$pkg_filenames" ] || fatal "Conflicts: Missing package(s) name"
+    epm_conflicts_files
+    epm_conflicts_names
 }
diff --git a/bin/epm-download b/bin/epm-download
--- a/bin/epm-download
+++ b/bin/epm-download
@@ -21,267 +21,267 @@ alt_base_dist_url="http://ftp.basealt.ru/pub/distributions"
 
 __use_url_install()
 {
-	# force download if wildcard is used
-	echo "$pkg_urls" | grep -q "[?*]" && return 1
+    # force download if wildcard is used
+    echo "$pkg_urls" | grep -q "[?*]" && return 1
 
-	# install of remote files has a side affect
-	# (more fresh package from a repo can be installed instead of the file)
-	#case $DISTRNAME in
-	#	"ALTLinux")
-	#		# do not support https yet
-	#		echo "$pkg_urls" | grep -q "https://" && return 1
-	#		pkg_names="$pkg_names $pkg_urls"
-	#		return 0
-	#		;;
-	#esac
+    # install of remote files has a side affect
+    # (more fresh package from a repo can be installed instead of the file)
+    #case $DISTRNAME in
+    #    "ALTLinux")
+    #        # do not support https yet
+    #        echo "$pkg_urls" | grep -q "https://" && return 1
+    #        pkg_names="$pkg_names $pkg_urls"
+    #        return 0
+    #        ;;
+    #esac
 
-	case $PMTYPE in
-		#apt-rpm)
-		#	pkg_names="$pkg_names $pkg_urls"
-		#	;;
-		#deepsolver-rpm)
-		#	pkg_names="$pkg_names $pkg_urls"
-		#	;;
-		#urpm-rpm)
-		#	pkg_names="$pkg_names $pkg_urls"
-		#	;;
-		pacman)
-			pkg_names="$pkg_names $pkg_urls"
-			;;
-		yum-rpm|dnf-rpm)
-			pkg_names="$pkg_names $pkg_urls"
-			;;
-		#zypper-rpm)
-		#	pkg_names="$pkg_names $pkg_urls"
-		#	;;
-		*)
-			return 1
-			;;
-	esac
-	return 0
+    case $PMTYPE in
+        #apt-rpm)
+        #    pkg_names="$pkg_names $pkg_urls"
+        #    ;;
+        #deepsolver-rpm)
+        #    pkg_names="$pkg_names $pkg_urls"
+        #    ;;
+        #urpm-rpm)
+        #    pkg_names="$pkg_names $pkg_urls"
+        #    ;;
+        pacman)
+            pkg_names="$pkg_names $pkg_urls"
+            ;;
+        yum-rpm|dnf-rpm)
+            pkg_names="$pkg_names $pkg_urls"
+            ;;
+        #zypper-rpm)
+        #    pkg_names="$pkg_names $pkg_urls"
+        #    ;;
+        *)
+            return 1
+            ;;
+    esac
+    return 0
 }
 
 # for download before install / checking
 __download_pkg_urls()
 {
-	local url
-	[ -z "$pkg_urls" ] && return
-	for url in $pkg_urls ; do
-		local tmppkg=$(mktemp -d) || fatal "failed mktemp -d"
-		docmd chmod $verbose a+rX $tmppkg
-		showcmd cd $tmppkg
-		cd $tmppkg || fatal
-		local latest='--latest'
-		# hack: download all if mask is *.something
-		basename "$url" | grep -q "^\*\." && latest=''
-		# download packages
-		if docmd eget $latest "$url" ; then
-			local i
-			for i in *.* ; do
-				[ -s "$tmppkg/$i" ] || continue
-				chmod $verbose a+r "$tmppkg/$i"
-				pkg_files="$pkg_files $tmppkg/$i"
-				to_remove_pkg_files="$to_remove_pkg_files $tmppkg/$i"
-			done
-		else
-			warning "Failed to download $url, ignoring"
-		fi
-		cd - >/dev/null
-	done
-	# reconstruct
-	pkg_filenames=$(strip_spaces "$pkg_files $pkg_names")
+    local url
+    [ -z "$pkg_urls" ] && return
+    for url in $pkg_urls ; do
+        local tmppkg=$(mktemp -d) || fatal "failed mktemp -d"
+        docmd chmod $verbose a+rX $tmppkg
+        showcmd cd $tmppkg
+        cd $tmppkg || fatal
+        local latest='--latest'
+        # hack: download all if mask is *.something
+        basename "$url" | grep -q "^\*\." && latest=''
+        # download packages
+        if docmd eget $latest "$url" ; then
+            local i
+            for i in *.* ; do
+                [ -s "$tmppkg/$i" ] || continue
+                chmod $verbose a+r "$tmppkg/$i"
+                pkg_files="$pkg_files $tmppkg/$i"
+                to_remove_pkg_files="$to_remove_pkg_files $tmppkg/$i"
+            done
+        else
+            warning "Failed to download $url, ignoring"
+        fi
+        cd - >/dev/null
+    done
+    # reconstruct
+    pkg_filenames=$(strip_spaces "$pkg_files $pkg_names")
 }
 
 # NOTE: call __clean_downloaded_pkg_files after
 __handle_pkg_urls_to_install()
 {
-	#[ -n "$pkg_urls" ] || return
+    #[ -n "$pkg_urls" ] || return
 
-	# TODO: do it correctly
-	to_remove_pkg_files=
-	# FIXME: check type of pkg_urls separately?
-	if [ "$(get_package_type "$pkg_urls")" != $PKGFORMAT ] || ! __use_url_install ; then
-		# use workaround with eget: download and put in pkg_files
-		__download_pkg_urls
-	fi
+    # TODO: do it correctly
+    to_remove_pkg_files=
+    # FIXME: check type of pkg_urls separately?
+    if [ "$(get_package_type "$pkg_urls")" != $PKGFORMAT ] || ! __use_url_install ; then
+        # use workaround with eget: download and put in pkg_files
+        __download_pkg_urls
+    fi
 
-	pkg_urls=
+    pkg_urls=
 }
 
 __handle_pkg_urls_to_checking()
 {
-	#[ -n "$pkg_urls" ] || return
+    #[ -n "$pkg_urls" ] || return
 
-	# TODO: do it correctly
-	to_remove_pkg_files=
-	
-	# use workaround with eget: download and put in pkg_files
-	__download_pkg_urls
+    # TODO: do it correctly
+    to_remove_pkg_files=
+    
+    # use workaround with eget: download and put in pkg_files
+    __download_pkg_urls
 
-	pkg_urls=
+    pkg_urls=
 }
 
 #__clean_downloaded_pkg_files()
 #{
-#	[ -z "$to_remove_pkg_files" ] && return
-#	rm -fv $to_remove_pkg_files
+#    [ -z "$to_remove_pkg_files" ] && return
+#    rm -fv $to_remove_pkg_files
 #}
 
 # obsoleted
 __epm_get_altpkg_url()
 {
-	info "TODO: https://packages.altlinux.org/api/branches"
-	load_helper epm-site
-	local arch=$(paoapi packages/$1 | get_pao_var arch)
-	# FIXME: arch can be list
-	[ "$arch" = "noarch" ] || arch=$(arch)
-	# HACK: filename can be list
-	local filename=$(paoapi packages/$1 | get_pao_var filename | grep $arch)
-	[ -n "$filename" ] || fatal "Can't get filename"
-	# fixme: get from /branches
-	local dv=$DISTRNAME/$DISTRVERSION/branch
-	[ "$DISTRVERSION" = "Sisyphus" ] && dv=$DISTRNAME/$DISTRVERSION
-	echo "$alt_base_dist_url/$dv/$arch/RPMS.classic/$filename"
+    info "TODO: https://packages.altlinux.org/api/branches"
+    load_helper epm-site
+    local arch=$(paoapi packages/$1 | get_pao_var arch)
+    # FIXME: arch can be list
+    [ "$arch" = "noarch" ] || arch=$(arch)
+    # HACK: filename can be list
+    local filename=$(paoapi packages/$1 | get_pao_var filename | grep $arch)
+    [ -n "$filename" ] || fatal "Can't get filename"
+    # fixme: get from /branches
+    local dv=$DISTRNAME/$DISTRVERSION/branch
+    [ "$DISTRVERSION" = "Sisyphus" ] && dv=$DISTRNAME/$DISTRVERSION
+    echo "$alt_base_dist_url/$dv/$arch/RPMS.classic/$filename"
 }
 
 # obsoleted
 __epm_print_url_alt()
 {
-	local url="$1"
-	echo "$url"
-	echo "$url" | sed -e "s|$alt_base_dist_url/$DISTRNAME|http://mirror.yandex.ru/altlinux|g"
-	echo "$url" | sed -e "s|$alt_base_dist_url/$DISTRNAME|http://download.etersoft.ru/pub/ALTLinux|g"
+    local url="$1"
+    echo "$url"
+    echo "$url" | sed -e "s|$alt_base_dist_url/$DISTRNAME|http://mirror.yandex.ru/altlinux|g"
+    echo "$url" | sed -e "s|$alt_base_dist_url/$DISTRNAME|http://download.etersoft.ru/pub/ALTLinux|g"
 }
 
 __epm_print_url_alt_check()
 {
-	local pkg=$1
-	shift
-	local tm=$(mktemp)
-	assure_exists curl
-	load_helper epm-site
-	quiet=1
-	local buildtime=$(paoapi packages/$pkg | get_pao_var buildtime)
-	echo
-	echo "Latest release: $(paoapi packages/$pkg | get_pao_var sourcepackage) $buildtime"
-	__epm_print_url_alt "$1" | while read url ; do
-		a='' curl -s --head $url >$tm || { echo "$url: missed" ; continue ; }
-		local http=$(cat $tm | grep "^HTTP" | sed -e "s|\r||g")
-		local lastdate=$(cat $tm | grep "^Last-Modified:" | sed -e "s|\r||g")
-		local size=$(cat $tm | grep "^Content-Length:" | sed -e "s|^Content-Length: ||g"  | sed -e "s|\r||g")
-		echo "$url ($http $lastdate) Size: $size"
-	done
-	rm -f $tm
+    local pkg=$1
+    shift
+    local tm=$(mktemp)
+    assure_exists curl
+    load_helper epm-site
+    quiet=1
+    local buildtime=$(paoapi packages/$pkg | get_pao_var buildtime)
+    echo
+    echo "Latest release: $(paoapi packages/$pkg | get_pao_var sourcepackage) $buildtime"
+    __epm_print_url_alt "$1" | while read url ; do
+        a='' curl -s --head $url >$tm || { echo "$url: missed" ; continue ; }
+        local http=$(cat $tm | grep "^HTTP" | sed -e "s|\r||g")
+        local lastdate=$(cat $tm | grep "^Last-Modified:" | sed -e "s|\r||g")
+        local size=$(cat $tm | grep "^Content-Length:" | sed -e "s|^Content-Length: ||g"  | sed -e "s|\r||g")
+        echo "$url ($http $lastdate) Size: $size"
+    done
+    rm -f $tm
 }
 
 __epm_download_alt()
 {
-	local pkg
-	if [ "$1" = "--check" ] ; then
-		local checkflag="$1"
-		shift
-	fi
+    local pkg
+    if [ "$1" = "--check" ] ; then
+        local checkflag="$1"
+        shift
+    fi
 
-	load_helper epm-sh-altlinux
+    load_helper epm-sh-altlinux
 
-	# TODO: enable if install --download-only will works
-	if tasknumber "$@" >/dev/null ; then
-		load_helper epm-addrepo
-		load_helper epm-reposave
-		load_helper epm-removerepo
-		load_helper epm-Install
+    # TODO: enable if install --download-only will works
+    if tasknumber "$@" >/dev/null ; then
+        load_helper epm-addrepo
+        load_helper epm-reposave
+        load_helper epm-removerepo
+        load_helper epm-Install
 
-		local installlist="$(get_task_packages $*)"
-		# hack: drop -devel packages to avoid package provided by multiple packages
-		installlist="$(estrlist reg_exclude ".*-devel .*-devel-static .*-checkinstall .*-debuginfo" "$installlist")"
-		[ -n "$verbose" ] && info "Packages from task(s): $installlist"
+        local installlist="$(get_task_packages $*)"
+        # hack: drop -devel packages to avoid package provided by multiple packages
+        installlist="$(estrlist reg_exclude ".*-devel .*-devel-static .*-checkinstall .*-debuginfo" "$installlist")"
+        [ -n "$verbose" ] && info "Packages from task(s): $installlist"
 
-		try_change_alt_repo
-		epm_addrepo "$@"
-		epm update
-		[ -n "$verbose" ] && epm repo list
-		docmd epm download $print_url $installlist
-		epm_removerepo "$@"
-		end_change_alt_repo
+        try_change_alt_repo
+        epm_addrepo "$@"
+        epm update
+        [ -n "$verbose" ] && epm repo list
+        docmd epm download $print_url $installlist
+        epm_removerepo "$@"
+        end_change_alt_repo
 
-		return
-	fi
+        return
+    fi
 
     # old systems ignore reinstall ?
-	for pkg in "$@" ; do
-		for i in $(sudocmd apt-get install -y --print-uris --reinstall "$pkg" | cut -f1 -d " " | grep ".rpm'$" | sed -e "s|^'||" -e "s|'$||") ; do
-			echo "$(basename "$i")" | grep -q "^$pkg" || continue
-			[ -n "$print_url" ] && echo "$i" && continue
-			eget "$i"
-		done
-	done
-	return
+    for pkg in "$@" ; do
+        for i in $(sudocmd apt-get install -y --print-uris --reinstall "$pkg" | cut -f1 -d " " | grep ".rpm'$" | sed -e "s|^'||" -e "s|'$||") ; do
+            echo "$(basename "$i")" | grep -q "^$pkg" || continue
+            [ -n "$print_url" ] && echo "$i" && continue
+            eget "$i"
+        done
+    done
+    return
 
-	# old code:
-	for pkg in "$@" ; do
-		local url=$(__epm_get_altpkg_url $pkg)
-		[ -n "$url" ] || warning "Can't get URL for $pkg"
-		if [ -n "$checkflag" ] ; then
-			__epm_print_url_alt_check "$pkg" "$url"
-		else
-			docmd eget $url || return
-		fi
-	done
+    # old code:
+    for pkg in "$@" ; do
+        local url=$(__epm_get_altpkg_url $pkg)
+        [ -n "$url" ] || warning "Can't get URL for $pkg"
+        if [ -n "$checkflag" ] ; then
+            __epm_print_url_alt_check "$pkg" "$url"
+        else
+            docmd eget $url || return
+        fi
+    done
 }
 
 epm_download()
 {
-	local CMD
+    local CMD
 
-	case "$BASEDISTRNAME" in
-		"alt")
-			__epm_download_alt $*
-			return
-			;;
-	esac
+    case "$BASEDISTRNAME" in
+        "alt")
+            __epm_download_alt $*
+            return
+            ;;
+    esac
 
-	case $PMTYPE in
-	apt-dpkg)
-		if [ -n "$print_url" ] ; then
-			docmd apt-get download --print-uris $* | cut -f1 -d " " | grep ".deb'$" | sed -e "s|^'||" -e "s|'$||"
-			return
-		fi
-		docmd apt-get download $*
-		;;
-	dnf-rpm)
-		sudocmd dnf download $print_url $*
-		;;
-	aptcyg)
-		sudocmd apt-cyg download $*
-		;;
-	packagekit)
-		docmd pkcon download $*
-		;;
-	yum-rpm)
-		# TODO: check yum install --downloadonly --downloaddir=/tmp <package-name>
-		assure_exists yumdownloader yum-utils
-		sudocmd yumdownloader $*
-		;;
-	dnf-rpm)
-		sudocmd dnf download $*
-		;;
-	urpm-rpm)
-		sudocmd urpmi --no-install $URPMOPTIONS $@
-		;;
-	tce)
-		sudocmd tce-load -w $*
-		;;
-	opkg)
-		docmd opkg $*
-		;;
-	eopkg)
-		docmd eopkg fetch $*
-		;;
-	homebrew)
-		docmd brew fetch $*
-		;;
-	*)
-		fatal "Have no suitable command for $PMTYPE"
-		;;
-	esac
+    case $PMTYPE in
+    apt-dpkg)
+        if [ -n "$print_url" ] ; then
+            docmd apt-get download --print-uris $* | cut -f1 -d " " | grep ".deb'$" | sed -e "s|^'||" -e "s|'$||"
+            return
+        fi
+        docmd apt-get download $*
+        ;;
+    dnf-rpm)
+        sudocmd dnf download $print_url $*
+        ;;
+    aptcyg)
+        sudocmd apt-cyg download $*
+        ;;
+    packagekit)
+        docmd pkcon download $*
+        ;;
+    yum-rpm)
+        # TODO: check yum install --downloadonly --downloaddir=/tmp <package-name>
+        assure_exists yumdownloader yum-utils
+        sudocmd yumdownloader $*
+        ;;
+    dnf-rpm)
+        sudocmd dnf download $*
+        ;;
+    urpm-rpm)
+        sudocmd urpmi --no-install $URPMOPTIONS $@
+        ;;
+    tce)
+        sudocmd tce-load -w $*
+        ;;
+    opkg)
+        docmd opkg $*
+        ;;
+    eopkg)
+        docmd eopkg fetch $*
+        ;;
+    homebrew)
+        docmd brew fetch $*
+        ;;
+    *)
+        fatal "Have no suitable command for $PMTYPE"
+        ;;
+    esac
 }
diff --git a/bin/epm-full_upgrade b/bin/epm-full_upgrade
--- a/bin/epm-full_upgrade
+++ b/bin/epm-full_upgrade
@@ -19,8 +19,8 @@
 
 epm_full_upgrade_help()
 {
-			get_help HELPCMD $SHAREDIR/epm-full_upgrade
-	cat <<EOF
+            get_help HELPCMD $SHAREDIR/epm-full_upgrade
+    cat <<EOF
 Also you can comment out full_upgrade parts in /etc/eepm/eepm.conf config.
 Examples:
   epm full-upgrade
@@ -32,60 +32,60 @@ EOF
 epm_full_upgrade()
 {
 
-	while [ -n "$1" ] ; do
-		case "$1" in
-			"-h"|"--help"|"help")      # HELPCMD: help
-				epm_full_upgrade_help
-				return
-				;;
-			"--no-epm-play")           # HELPCMD: skip epm play during full upgrade
-				full_upgrade_no_epm_play=1
-				;;
-			"--no-flatpack")           # HELPCMD: skip flatpack update during full upgrade
-				full_upgrade_no_flatpack=1
-				;;
-			"--no-snap")           # HELPCMD: skip snap update during full upgrade
-				full_upgrade_no_snap=1
-				;;
-			"--no-kernel-update")  # HELPCMD: skip kernel update during full upgrade
-				full_upgrade_no_kernel_update=1
-				;;
-		esac
-		shift
-	done
+    while [ -n "$1" ] ; do
+        case "$1" in
+            "-h"|"--help"|"help")      # HELPCMD: help
+                epm_full_upgrade_help
+                return
+                ;;
+            "--no-epm-play")           # HELPCMD: skip epm play during full upgrade
+                full_upgrade_no_epm_play=1
+                ;;
+            "--no-flatpack")           # HELPCMD: skip flatpack update during full upgrade
+                full_upgrade_no_flatpack=1
+                ;;
+            "--no-snap")           # HELPCMD: skip snap update during full upgrade
+                full_upgrade_no_snap=1
+                ;;
+            "--no-kernel-update")  # HELPCMD: skip kernel update during full upgrade
+                full_upgrade_no_kernel_update=1
+                ;;
+        esac
+        shift
+    done
 
-	docmd epm update || fatal "repository updating is failed."
+    docmd epm update || fatal "repository updating is failed."
 
-	[ -n "$quiet" ] || echo
-	docmd epm upgrade || fatal "upgrading of the system is failed."
+    [ -n "$quiet" ] || echo
+    docmd epm upgrade || fatal "upgrading of the system is failed."
 
-	if [ -z "$full_upgrade_no_kernel_update" ] ; then
-		[ -n "$quiet" ] || echo
-		docmd epm update-kernel || fatal "updating of the kernel is failed."
-	fi
+    if [ -z "$full_upgrade_no_kernel_update" ] ; then
+        [ -n "$quiet" ] || echo
+        docmd epm update-kernel || fatal "updating of the kernel is failed."
+    fi
 
-	# disable epm play --update for non ALT Systems
-	[ "$BASEDISTRNAME" = "alt" ] || full_upgrade_no_epm_play=1
+    # disable epm play --update for non ALT Systems
+    [ "$BASEDISTRNAME" = "alt" ] || full_upgrade_no_epm_play=1
 
-	if [ -z "$full_upgrade_no_epm_play" ] ; then
-		[ -n "$quiet" ] || echo
-		docmd epm play --update all || fatal "updating of applications installed via epm play is failed."
-	fi
+    if [ -z "$full_upgrade_no_epm_play" ] ; then
+        [ -n "$quiet" ] || echo
+        docmd epm play --update all || fatal "updating of applications installed via epm play is failed."
+    fi
 
-	if [ -z "$full_upgrade_no_flatpack" ] ; then
-		if is_command flatpak ; then
-			[ -n "$quiet" ] || echo
-			docmd flatpak update
-		fi
-	fi
+    if [ -z "$full_upgrade_no_flatpack" ] ; then
+        if is_command flatpak ; then
+            [ -n "$quiet" ] || echo
+            docmd flatpak update
+        fi
+    fi
 
-	if [ -z "$full_upgrade_no_snap" ] ; then
-		if is_command snap && serv snapd exists && serv snapd status >/dev/null ; then
-			[ -n "$quiet" ] || echo
-			sudocmd snap refresh
-		fi
-	fi
+    if [ -z "$full_upgrade_no_snap" ] ; then
+        if is_command snap && serv snapd exists && serv snapd status >/dev/null ; then
+            [ -n "$quiet" ] || echo
+            sudocmd snap refresh
+        fi
+    fi
 
-	[ -n "$quiet" ] || echo
-	docmd epm clean
+    [ -n "$quiet" ] || echo
+    docmd epm clean
 }
diff --git a/bin/epm-install-emerge b/bin/epm-install-emerge
--- a/bin/epm-install-emerge
+++ b/bin/epm-install-emerge
@@ -26,73 +26,73 @@
 # install one ebuild
 __emerge_install_ebuild()
 {
-	local EBUILD="$1"
-	[ -s "$EBUILD" ] || fatal ".ebuild file '$EBUILD' is missed"
+    local EBUILD="$1"
+    [ -s "$EBUILD" ] || fatal ".ebuild file '$EBUILD' is missed"
 
-	# load ebuild and get vars
-	. $(pwd)/$EBUILD
-	[ -n "$SRC_URI" ] || fatal "Can't load SRC_URI from $EBUILD"
+    # load ebuild and get vars
+    . $(pwd)/$EBUILD
+    [ -n "$SRC_URI" ] || fatal "Can't load SRC_URI from $EBUILD"
 
-	# try to detect tarballs
-	local TARBALLS=
-	local BASEDIR=$(dirname $EBUILD)
-	for i in $SRC_URI ; do
-		[ -s "$BASEDIR/$(basename $i)" ] || continue
-		TARBALLS="$TARBALLS $BASEDIR/$(basename $i)"
-	done
+    # try to detect tarballs
+    local TARBALLS=
+    local BASEDIR=$(dirname $EBUILD)
+    for i in $SRC_URI ; do
+        [ -s "$BASEDIR/$(basename $i)" ] || continue
+        TARBALLS="$TARBALLS $BASEDIR/$(basename $i)"
+    done
 
-	local PORTAGENAME=epm
-	local LP=/usr/local/portage/$PORTAGENAME
-	docmd mkdir -p $LP/
-	MAKECONF=/etc/portage/make.conf
-	[ -r "$MAKECONF" ] || MAKECONF=/etc/make.conf
-	if ! grep -v "^#" $MAKECONF | grep -q $LP ; then
-		echo "PORTDIR_OVERLAY=\"$LP \${PORTDIR_OVERLAY}\"" >>$MAKECONF
-		# Overlay name
-		mkdir -p $LP/profiles/
-		echo "$PORTAGENAME" > $LP/profiles/repo_name
-	fi
+    local PORTAGENAME=epm
+    local LP=/usr/local/portage/$PORTAGENAME
+    docmd mkdir -p $LP/
+    MAKECONF=/etc/portage/make.conf
+    [ -r "$MAKECONF" ] || MAKECONF=/etc/make.conf
+    if ! grep -v "^#" $MAKECONF | grep -q $LP ; then
+        echo "PORTDIR_OVERLAY=\"$LP \${PORTDIR_OVERLAY}\"" >>$MAKECONF
+        # Overlay name
+        mkdir -p $LP/profiles/
+        echo "$PORTAGENAME" > $LP/profiles/repo_name
+    fi
 
-	# copy tarballs
-	local DDIR=/usr/portage/distfiles
-	# FIXME: use independent dir
-	[ -d /var/calculate/remote/distfiles ] && DDIR=/var/calculate/remote/distfiles
-	docmd cp -f $TARBALLS $DDIR/ || return
+    # copy tarballs
+    local DDIR=/usr/portage/distfiles
+    # FIXME: use independent dir
+    [ -d /var/calculate/remote/distfiles ] && DDIR=/var/calculate/remote/distfiles
+    docmd cp -f $TARBALLS $DDIR/ || return
 
-	# copy ebuild
-	docmd cp -f $EBUILD $LP/ || return
-	cd $LP
-	docmd ebuild $(basename $EBUILD) digest
-	cd -
-	# FIXME: more correcty get name
-	local PKGNAME=$(echo $EBUILD | sed -e "s|-[0-9].*||g")
-	docmd emerge -av $PKGNAME || return
+    # copy ebuild
+    docmd cp -f $EBUILD $LP/ || return
+    cd $LP
+    docmd ebuild $(basename $EBUILD) digest
+    cd -
+    # FIXME: more correcty get name
+    local PKGNAME=$(echo $EBUILD | sed -e "s|-[0-9].*||g")
+    docmd emerge -av $PKGNAME || return
 }
 
 # install one ebuild
 __emerge_install_tbz2()
 {
-	local TGDIR=/usr/portage/packages/app-arch
-	mkdir -p $TGDIR
-	cp $i $TGDIR || return
-	docmd emerge --usepkg $TGDIR/$(basename $i) || return
+    local TGDIR=/usr/portage/packages/app-arch
+    mkdir -p $TGDIR
+    cp $i $TGDIR || return
+    docmd emerge --usepkg $TGDIR/$(basename $i) || return
 }
 
 # install ebuild list
 epm_install_emerge()
 {
-	local EBUILD=
-	#local TARBALLS=
-	local i
+    local EBUILD=
+    #local TARBALLS=
+    local i
 
-	# search ebuild in the args
-	for i in $* ; do
-		if echo $i | grep -q ebuild ; then
-			__emerge_install_ebuild $i || return
-		elif echo $i | grep -q "\.tbz2$" ; then
-			__emerge_install_tbz2 $i || return
-	#	else
-	#		TARBALLS="$TARBALLS $i"
-		fi
-	done
+    # search ebuild in the args
+    for i in $* ; do
+        if echo $i | grep -q ebuild ; then
+            __emerge_install_ebuild $i || return
+        elif echo $i | grep -q "\.tbz2$" ; then
+            __emerge_install_tbz2 $i || return
+    #    else
+    #        TARBALLS="$TARBALLS $i"
+        fi
+    done
 }
diff --git a/bin/epm-pack b/bin/epm-pack
--- a/bin/epm-pack
+++ b/bin/epm-pack
@@ -26,73 +26,73 @@ load_helper epm-repack
 
 __epm_pack()
 {
-	local packname="$1"
-	local tarname="$2"
-	returntarname=''
+    local packname="$1"
+    local tarname="$2"
+    returntarname=''
 
-	local repackcode="$EPM_PACK_SCRIPTS_DIR/$packname.sh"
-	[ -x "$repackcode" ] || fatal "Can't find script $repackcode for packname $packname"
-	[ -f "$repackcode.rpmnew" ] && warning "There is .rpmnew file(s) in $EPM_PACK_SCRIPTS_DIR dir. The pack script can be outdated."
+    local repackcode="$EPM_PACK_SCRIPTS_DIR/$packname.sh"
+    [ -x "$repackcode" ] || fatal "Can't find script $repackcode for packname $packname"
+    [ -f "$repackcode.rpmnew" ] && warning "There is .rpmnew file(s) in $EPM_PACK_SCRIPTS_DIR dir. The pack script can be outdated."
 
-	tmpdir=$(mktemp -d)
-	filefortarname="$tmpdir/filefortarname"
-	trap "rm -rf $tmpdir" EXIT
+    tmpdir=$(mktemp -d)
+    filefortarname="$tmpdir/filefortarname"
+    trap "rm -rf $tmpdir" EXIT
 
-	set_sudo
-	export SUDO
+    set_sudo
+    export SUDO
 
-	# TODO: inside () ?
-	export PATH=$PROGDIR:$PATH
+    # TODO: inside () ?
+    export PATH=$PROGDIR:$PATH
 
-	local bashopt=''
-	[ -n "$verbose" ] && bashopt='-x'
-	#info "Running $($script --description 2>/dev/null) ..."
-	( unset EPMCURDIR ; docmd $CMDSHELL $bashopt $repackcode "$tarname" "$filefortarname" ) || fatal
-	returntarname="$(cat "$filefortarname")" || fatal "pack script $repackcode didn't set tarname"
-	rm -rf $tmpdir
+    local bashopt=''
+    [ -n "$verbose" ] && bashopt='-x'
+    #info "Running $($script --description 2>/dev/null) ..."
+    ( unset EPMCURDIR ; docmd $CMDSHELL $bashopt $repackcode "$tarname" "$filefortarname" ) || fatal
+    returntarname="$(cat "$filefortarname")" || fatal "pack script $repackcode didn't set tarname"
+    rm -rf $tmpdir
 
-	[ -s "$returntarname" ] || fatal "pack script $repackcode didn't return tarname"
+    [ -s "$returntarname" ] || fatal "pack script $repackcode didn't return tarname"
 
-	#local newname="$(basename "$returntarname")"
+    #local newname="$(basename "$returntarname")"
 
-	# now it is by default in the current dir
-	#if [ "$returntarname" != "$(realpath $newname)" ; then
-	#	# repack put its result to the current dir
-	#	mv -v $returntarname . || fatal
-	#fi
+    # now it is by default in the current dir
+    #if [ "$returntarname" != "$(realpath $newname)" ; then
+    #    # repack put its result to the current dir
+    #    mv -v $returntarname . || fatal
+    #fi
 
-	if [ -n "$download_only" ] ; then
-		return
-	fi
+    if [ -n "$download_only" ] ; then
+        return
+    fi
 
-	trap "rm -v $returntarname" EXIT
+    trap "rm -v $returntarname" EXIT
 
-	# FIXME: __epm_repack will drop trap
-	repacked_pkgs=''
-	# repack to our target
-	if __epm_repack_if_needed $returntarname ; then
-		[ -n "$repacked_pkgs" ] || fatal "Can't repack $returntarname"
-	# if repack is forced or repack rule (not disabled) is exists
-	elif [ -n "$repack" ] || [ -z "$norepack" ] && __epm_have_repack_rule $returntarname ; then
-		__epm_repack "$returntarname"
-		[ -n "$repacked_pkgs" ] || fatal "Can't repack $returntarname"
-	fi
+    # FIXME: __epm_repack will drop trap
+    repacked_pkgs=''
+    # repack to our target
+    if __epm_repack_if_needed $returntarname ; then
+        [ -n "$repacked_pkgs" ] || fatal "Can't repack $returntarname"
+    # if repack is forced or repack rule (not disabled) is exists
+    elif [ -n "$repack" ] || [ -z "$norepack" ] && __epm_have_repack_rule $returntarname ; then
+        __epm_repack "$returntarname"
+        [ -n "$repacked_pkgs" ] || fatal "Can't repack $returntarname"
+    fi
 
-	if [ -n "$repacked_pkgs" ] ; then
-		rm -v $returntarname
-		mv -v $repacked_pkgs . || fatal
-		pkgname=$(pwd)/"$(basename $repacked_pkgs)"
-	else
-		pkgname="$returntarname"
-	fi
+    if [ -n "$repacked_pkgs" ] ; then
+        rm -v $returntarname
+        mv -v $repacked_pkgs . || fatal
+        pkgname=$(pwd)/"$(basename $repacked_pkgs)"
+    else
+        pkgname="$returntarname"
+    fi
 
-	if [ -n "$install" ] ; then
-		trap "rm -v $pkgname" EXIT
-		docmd epm install $pkgname
-		return
-	fi
+    if [ -n "$install" ] ; then
+        trap "rm -v $pkgname" EXIT
+        docmd epm install $pkgname
+        return
+    fi
 
-	trap "" EXIT
+    trap "" EXIT
 
 }
 
diff --git a/bin/epm-remove b/bin/epm-remove
--- a/bin/epm-remove
+++ b/bin/epm-remove
@@ -35,323 +35,323 @@ __check_rpm_e_result()
 # Try remove with low level removing
 epm_remove_low()
 {
-	[ -z "$1" ] && return
+    [ -z "$1" ] && return
 
-	warmup_lowbase
+    warmup_lowbase
 
-	case $PMTYPE in
-		*-rpm)
-			cd /tmp || fatal
-			__epm_check_vendor $@
-			store_output sudocmd rpm -ev $noscripts $nodeps $@
-			# rpm returns number of packages if failed on removing
-			__check_rpm_e_result $RC_STDOUT $?
-			RES=$?
-			clean_store_output
-			cd - >/dev/null
-			return $RES ;;
-		*-dpkg|-dpkg)
-			# shellcheck disable=SC2046
-			sudocmd dpkg -P $(subst_option nodeps --force-all) $(print_name "$@")
-			return ;;
-		pkgsrc)
-			sudocmd pkg_delete -r $@
-			return ;;
-		pkgng)
-			sudocmd pkg delete -R $@
-			return ;;
-		emerge)
-			sudocmd emerge --unmerge $@
-			return ;;
-		pacman)
-			sudocmd pacman -R $@
-			return ;;
-		eopkg)
-			sudocmd eopkg $(subst_option nodeps --ignore-dependency) remove $@
-			return ;;
-		appget|winget)
-			sudocmd $PMTYPE uninstall $@
-			return ;;
-		slackpkg)
-			sudocmd /sbin/removepkg $@
-			return ;;
-	esac
-	return 1
+    case $PMTYPE in
+        *-rpm)
+            cd /tmp || fatal
+            __epm_check_vendor $@
+            store_output sudocmd rpm -ev $noscripts $nodeps $@
+            # rpm returns number of packages if failed on removing
+            __check_rpm_e_result $RC_STDOUT $?
+            RES=$?
+            clean_store_output
+            cd - >/dev/null
+            return $RES ;;
+        *-dpkg|-dpkg)
+            # shellcheck disable=SC2046
+            sudocmd dpkg -P $(subst_option nodeps --force-all) $(print_name "$@")
+            return ;;
+        pkgsrc)
+            sudocmd pkg_delete -r $@
+            return ;;
+        pkgng)
+            sudocmd pkg delete -R $@
+            return ;;
+        emerge)
+            sudocmd emerge --unmerge $@
+            return ;;
+        pacman)
+            sudocmd pacman -R $@
+            return ;;
+        eopkg)
+            sudocmd eopkg $(subst_option nodeps --ignore-dependency) remove $@
+            return ;;
+        appget|winget)
+            sudocmd $PMTYPE uninstall $@
+            return ;;
+        slackpkg)
+            sudocmd /sbin/removepkg $@
+            return ;;
+    esac
+    return 1
 }
 
 epm_remove_names()
 {
-	[ -z "$1" ] && return
+    [ -z "$1" ] && return
 
-	warmup_bases
+    warmup_bases
 
-	local APTOPTIONS="$(subst_option non_interactive -y)"
+    local APTOPTIONS="$(subst_option non_interactive -y)"
 
-	case $PMTYPE in
-		apt-dpkg)
-			sudocmd apt-get remove --purge $APTOPTIONS $@
-			return ;;
-		aptitude-dpkg)
-			sudocmd aptitude purge $@
-			return ;;
-		apt-rpm)
-			sudocmd apt-get remove $APTOPTIONS $@
-			return ;;
-		packagekit)
-			docmd pkcon remove $@
-			return ;;
-		deepsolver-rpm)
-			sudocmd ds-remove $@
-			return ;;
-		urpm-rpm)
-			sudocmd urpme $@
-			return ;;
-		pkgsrc) # without dependencies
-			sudocmd pkg_delete $@
-			return ;;
-		pkgng)
-			sudocmd pkg delete -R $@
-			return ;;
-		emerge)
-			#sudocmd emerge --unmerge $@
-			sudocmd emerge -aC $@
-			return ;;
-		pacman)
-			sudocmd pacman -Rc $@
-			return ;;
-		yum-rpm)
-			sudocmd yum remove $@
-			return ;;
-		dnf-rpm)
-			sudocmd dnf remove $@
-			return ;;
-		snappy)
-			sudocmd snappy uninstall $@
-			return ;;
-		zypper-rpm)
-			sudocmd zypper remove --clean-deps $@
-			return ;;
-		mpkg)
-			sudocmd mpkg remove $@
-			return ;;
-		eopkg)
-			sudocmd eopkg $(subst_option nodeps --ignore-dependency) remove $@
-			return ;;
-		conary)
-			sudocmd conary erase $@
-			return ;;
-		npackd)
-			sudocmd npackdcl remove --package=$1
-			return ;;
-		nix)
-			sudocmd nix-env --uninstall $@
-			return ;;
-		apk)
-			sudocmd apk del $@
-			return ;;
-		guix)
-			sudocmd guix package -r $@
-			return ;;
-		android)
-			sudocmd pm uninstall $@
-			return ;;
-		chocolatey)
-			sudocmd chocolatey uninstall $@
-			return ;;
-		slackpkg)
-			sudocmd /usr/sbin/slackpkg remove $@
-			return ;;
-		homebrew)
-			docmd brew remove $@
-			return ;;
-		aptcyg)
-			sudocmd apt-cyg remove $@
-			return ;;
-		xbps)
-			sudocmd xbps remove -R $@
-			return ;;
-		appget|winget)
-			sudocmd $PMTYPE uninstall $@
-			return ;;
-		opkg)
-			# shellcheck disable=SC2046
-			sudocmd opkg $(subst_option force -force-depends) remove $@
-			return ;;
-		*)
-			fatal "Have no suitable command for $PMTYPE"
-			;;
-	esac
+    case $PMTYPE in
+        apt-dpkg)
+            sudocmd apt-get remove --purge $APTOPTIONS $@
+            return ;;
+        aptitude-dpkg)
+            sudocmd aptitude purge $@
+            return ;;
+        apt-rpm)
+            sudocmd apt-get remove $APTOPTIONS $@
+            return ;;
+        packagekit)
+            docmd pkcon remove $@
+            return ;;
+        deepsolver-rpm)
+            sudocmd ds-remove $@
+            return ;;
+        urpm-rpm)
+            sudocmd urpme $@
+            return ;;
+        pkgsrc) # without dependencies
+            sudocmd pkg_delete $@
+            return ;;
+        pkgng)
+            sudocmd pkg delete -R $@
+            return ;;
+        emerge)
+            #sudocmd emerge --unmerge $@
+            sudocmd emerge -aC $@
+            return ;;
+        pacman)
+            sudocmd pacman -Rc $@
+            return ;;
+        yum-rpm)
+            sudocmd yum remove $@
+            return ;;
+        dnf-rpm)
+            sudocmd dnf remove $@
+            return ;;
+        snappy)
+            sudocmd snappy uninstall $@
+            return ;;
+        zypper-rpm)
+            sudocmd zypper remove --clean-deps $@
+            return ;;
+        mpkg)
+            sudocmd mpkg remove $@
+            return ;;
+        eopkg)
+            sudocmd eopkg $(subst_option nodeps --ignore-dependency) remove $@
+            return ;;
+        conary)
+            sudocmd conary erase $@
+            return ;;
+        npackd)
+            sudocmd npackdcl remove --package=$1
+            return ;;
+        nix)
+            sudocmd nix-env --uninstall $@
+            return ;;
+        apk)
+            sudocmd apk del $@
+            return ;;
+        guix)
+            sudocmd guix package -r $@
+            return ;;
+        android)
+            sudocmd pm uninstall $@
+            return ;;
+        chocolatey)
+            sudocmd chocolatey uninstall $@
+            return ;;
+        slackpkg)
+            sudocmd /usr/sbin/slackpkg remove $@
+            return ;;
+        homebrew)
+            docmd brew remove $@
+            return ;;
+        aptcyg)
+            sudocmd apt-cyg remove $@
+            return ;;
+        xbps)
+            sudocmd xbps remove -R $@
+            return ;;
+        appget|winget)
+            sudocmd $PMTYPE uninstall $@
+            return ;;
+        opkg)
+            # shellcheck disable=SC2046
+            sudocmd opkg $(subst_option force -force-depends) remove $@
+            return ;;
+        *)
+            fatal "Have no suitable command for $PMTYPE"
+            ;;
+    esac
 }
 
 # TODO
 epm_remove_nonint()
 {
-	warmup_bases
+    warmup_bases
 
-	case $PMTYPE in
-		apt-dpkg)
-			sudocmd apt-get -y --force-yes remove --purge $@
-			return ;;
-		aptitude-dpkg)
-			sudocmd aptitude -y purge $@
-			return ;;
-		apt-rpm)
-			sudocmd apt-get -y --force-yes remove $@
-			return ;;
-		packagekit)
-			docmd pkcon remove --noninteractive $@
-			return ;;
-		urpm-rpm)
-			sudocmd urpme --auto $@
-			return ;;
-		pacman)
-			sudocmd pacman -Rc --noconfirm $@
-			return ;;
-		yum-rpm)
-			sudocmd yum -y remove $@
-			return ;;
-		dnf-rpm)
-			sudocmd dnf remove --assumeyes $@
-			return ;;
-		zypper-rpm)
-			sudocmd zypper --non-interactive remove --clean-deps $@
-			return ;;
-		slackpkg)
-			sudocmd /usr/sbin/slackpkg -batch=on -default_answer=yes remove $@
-			return ;;
-		pkgng)
-			sudocmd pkg delete -y -R $@
-			return ;;
-		opkg)
-			sudocmd opkg -force-defaults remove $@
-			return ;;
-		eopkg)
-			sudocmd eopkg $(subst_option nodeps --ignore-dependency) --yes-all remove $@
-			return ;;
-		appget|winget)
-			sudocmd $PMTYPE uninstall -s $@
-			return ;;
-		xbps)
-			sudocmd xbps remove -y $@
-			return ;;
-	esac
-	return 5
+    case $PMTYPE in
+        apt-dpkg)
+            sudocmd apt-get -y --force-yes remove --purge $@
+            return ;;
+        aptitude-dpkg)
+            sudocmd aptitude -y purge $@
+            return ;;
+        apt-rpm)
+            sudocmd apt-get -y --force-yes remove $@
+            return ;;
+        packagekit)
+            docmd pkcon remove --noninteractive $@
+            return ;;
+        urpm-rpm)
+            sudocmd urpme --auto $@
+            return ;;
+        pacman)
+            sudocmd pacman -Rc --noconfirm $@
+            return ;;
+        yum-rpm)
+            sudocmd yum -y remove $@
+            return ;;
+        dnf-rpm)
+            sudocmd dnf remove --assumeyes $@
+            return ;;
+        zypper-rpm)
+            sudocmd zypper --non-interactive remove --clean-deps $@
+            return ;;
+        slackpkg)
+            sudocmd /usr/sbin/slackpkg -batch=on -default_answer=yes remove $@
+            return ;;
+        pkgng)
+            sudocmd pkg delete -y -R $@
+            return ;;
+        opkg)
+            sudocmd opkg -force-defaults remove $@
+            return ;;
+        eopkg)
+            sudocmd eopkg $(subst_option nodeps --ignore-dependency) --yes-all remove $@
+            return ;;
+        appget|winget)
+            sudocmd $PMTYPE uninstall -s $@
+            return ;;
+        xbps)
+            sudocmd xbps remove -y $@
+            return ;;
+    esac
+    return 5
 }
 
 epm_print_remove_command()
 {
-	case $PMTYPE in
-		*-rpm)
-			echo "rpm -ev $nodeps $*"
-			;;
-		*-dpkg)
-			echo "dpkg -P $*"
-			;;
-		packagekit-*)
-			echo "pkcon remove --noninteractive $*"
-			;;
-		pkgsrc)
-			echo "pkg_delete -r $*"
-			;;
-		pkgng)
-			echo "pkg delete -R $*"
-			;;
-		pacman)
-			echo "pacman -R $*"
-			;;
-		emerge)
-			echo "emerge --unmerge $*"
-			;;
-		slackpkg)
-			echo "/sbin/removepkg $*"
-			;;
-		opkg)
-			echo "opkg remove $*"
-			;;
-		eopkg)
-			echo "eopkg remove $*"
-			;;
-		aptcyg)
-			echo "apt-cyg remove $*"
-			;;
-		xbps)
-			echo "xbps remove -y $*"
-			;;
-		appget|winget)
-			echo "$PMTYPE uninstall -s $*"
-			;;
-		*)
-			fatal "Have no suitable appropriate remove command for $PMTYPE"
-			;;
-	esac
+    case $PMTYPE in
+        *-rpm)
+            echo "rpm -ev $nodeps $*"
+            ;;
+        *-dpkg)
+            echo "dpkg -P $*"
+            ;;
+        packagekit-*)
+            echo "pkcon remove --noninteractive $*"
+            ;;
+        pkgsrc)
+            echo "pkg_delete -r $*"
+            ;;
+        pkgng)
+            echo "pkg delete -R $*"
+            ;;
+        pacman)
+            echo "pacman -R $*"
+            ;;
+        emerge)
+            echo "emerge --unmerge $*"
+            ;;
+        slackpkg)
+            echo "/sbin/removepkg $*"
+            ;;
+        opkg)
+            echo "opkg remove $*"
+            ;;
+        eopkg)
+            echo "eopkg remove $*"
+            ;;
+        aptcyg)
+            echo "apt-cyg remove $*"
+            ;;
+        xbps)
+            echo "xbps remove -y $*"
+            ;;
+        appget|winget)
+            echo "$PMTYPE uninstall -s $*"
+            ;;
+        *)
+            fatal "Have no suitable appropriate remove command for $PMTYPE"
+            ;;
+    esac
 }
 
 
 epm_remove()
 {
-	if [ -n "$show_command_only" ] ; then
-		epm_print_remove_command $pkg_filenames
-		return
-	fi
+    if [ -n "$show_command_only" ] ; then
+        epm_print_remove_command $pkg_filenames
+        return
+    fi
 
-	if [ "$BASEDISTRNAME" = "alt" ] ; then
-		load_helper epm-sh-altlinux
-		if tasknumber "$pkg_names" >/dev/null ; then
-			assure_exists apt-repo
-			pkg_names="$(get_task_packages $pkg_names)"
-		fi
-	fi
+    if [ "$BASEDISTRNAME" = "alt" ] ; then
+        load_helper epm-sh-altlinux
+        if tasknumber "$pkg_names" >/dev/null ; then
+            assure_exists apt-repo
+            pkg_names="$(get_task_packages $pkg_names)"
+        fi
+    fi
 
-	# TODO: fix pkg_names override
-	# get full package name(s) from the package file(s)
-	[ -n "$pkg_files" ] && pkg_names="$pkg_names $(epm query $pkg_files)"
-	pkg_files=''
+    # TODO: fix pkg_names override
+    # get full package name(s) from the package file(s)
+    [ -n "$pkg_files" ] && pkg_names="$pkg_names $(epm query $pkg_files)"
+    pkg_files=''
 
-	if [ -z "$pkg_names" ] ; then
-		warning "no package(s) to remove."
-		return
-	fi
-	# remove according current arch (if x86_64) by default
-	pkg_names="$(echo $pkg_names | exp_with_arch_suffix)"
+    if [ -z "$pkg_names" ] ; then
+        warning "no package(s) to remove."
+        return
+    fi
+    # remove according current arch (if x86_64) by default
+    pkg_names="$(echo $pkg_names | exp_with_arch_suffix)"
 
-	if [ -n "$dryrun" ] ; then
-		info "Packages for removing:"
-		echo "$pkg_names"
-		case $PMTYPE in
-			apt-rpm)
-				nodeps="--test"
-				APTOPTIONS="--simulate"
-				;;
-			apt-deb)
-				nodeps="--simulate"
-				APTOPTIONS="--simulate"
-				;;
-			*)
-				return
-				;;
-		esac
-	fi
+    if [ -n "$dryrun" ] ; then
+        info "Packages for removing:"
+        echo "$pkg_names"
+        case $PMTYPE in
+            apt-rpm)
+                nodeps="--test"
+                APTOPTIONS="--simulate"
+                ;;
+            apt-deb)
+                nodeps="--simulate"
+                APTOPTIONS="--simulate"
+                ;;
+            *)
+                return
+                ;;
+        esac
+    fi
 
-	if [ -n "$skip_missed" ] ; then
-		pkg_names="$(get_only_installed_packages $pkg_names)"
-	fi
+    if [ -n "$skip_missed" ] ; then
+        pkg_names="$(get_only_installed_packages $pkg_names)"
+    fi
 
-	epm_remove_low $pkg_names && return
-	local STATUS=$?
+    epm_remove_low $pkg_names && return
+    local STATUS=$?
 
-	if [ -n "$direct" ] || [ -n "$nodeps" ] || [ "$STATUS" = "$RPMISNOTINSTALLED" ]; then
-		[ -n "$force" ] || return $STATUS
-	fi
+    if [ -n "$direct" ] || [ -n "$nodeps" ] || [ "$STATUS" = "$RPMISNOTINSTALLED" ]; then
+        [ -n "$force" ] || return $STATUS
+    fi
 
-	# get package name for hi level package management command (with version if supported and if possible)
-	pkg_names=$(__epm_get_hilevel_name $pkg_names)
+    # get package name for hi level package management command (with version if supported and if possible)
+    pkg_names=$(__epm_get_hilevel_name $pkg_names)
 
-	if [ -n "$non_interactive" ] ; then
-		epm_remove_nonint $pkg_names
-		local RET=$?
-		# if not separate command, use usual command
-		[ "$RET" = "5" ] || return $RET
-	fi
+    if [ -n "$non_interactive" ] ; then
+        epm_remove_nonint $pkg_names
+        local RET=$?
+        # if not separate command, use usual command
+        [ "$RET" = "5" ] || return $RET
+    fi
 
-	epm_remove_names $pkg_names
+    epm_remove_names $pkg_names
 }
diff --git a/bin/epm-repack b/bin/epm-repack
--- a/bin/epm-repack
+++ b/bin/epm-repack
@@ -48,18 +48,18 @@ __epm_check_if_needed_repack()
 # fills split_replaced_pkgs with packages of that type
 __epm_split_by_pkg_type()
 {
-	local type="$1"
-	shift
+    local type="$1"
+    shift
 
-	split_replaced_pkgs=''
+    split_replaced_pkgs=''
 
-	for pkg in "$@" ; do
-		[ "$(get_package_type "$pkg")" = "$type" ] || return 1
-		[ -e "$pkg" ] || fatal "Can't read $pkg"
-		split_replaced_pkgs="$split_replaced_pkgs $pkg"
-	done
+    for pkg in "$@" ; do
+        [ "$(get_package_type "$pkg")" = "$type" ] || return 1
+        [ -e "$pkg" ] || fatal "Can't read $pkg"
+        split_replaced_pkgs="$split_replaced_pkgs $pkg"
+    done
 
-	[ -n "$split_replaced_pkgs" ]
+    [ -n "$split_replaced_pkgs" ]
 }
 
 
@@ -181,43 +181,43 @@ __prepare_source_package()
 # fill repacked_pkgs
 __epm_repack()
 {
-	repacked_pkgs=''
-	case $PKGFORMAT in
-		rpm)
-			load_helper epm-repack-rpm
-			__epm_repack_to_rpm "$@" || return
-			;;
-		deb)
-			# FIXME: only one package in $@ is supported
-			#local pkgname="$(epm print name from "$@")"
-			__set_version_pkgname "$1"
-			local repackcode="$EPM_REPACK_SCRIPTS_DIR/$PKGNAME.sh"
-			if [ -x "$repackcode" ] ; then
-				load_helper epm-repack-rpm
-				load_helper epm-repack-deb
-				__epm_repack_to_rpm "$@" || return
-				[ -n "$repacked_pkgs" ] || return
-				__epm_repack_to_deb $repacked_pkgs
-			else
-				load_helper epm-repack-deb
-				__epm_repack_to_deb "$@" || return
-			fi
-			;;
-		*)
-			fatal "$PKGFORMAT is not supported for repack yet"
-			;;
-	esac
+    repacked_pkgs=''
+    case $PKGFORMAT in
+        rpm)
+            load_helper epm-repack-rpm
+            __epm_repack_to_rpm "$@" || return
+            ;;
+        deb)
+            # FIXME: only one package in $@ is supported
+            #local pkgname="$(epm print name from "$@")"
+            __set_version_pkgname "$1"
+            local repackcode="$EPM_REPACK_SCRIPTS_DIR/$PKGNAME.sh"
+            if [ -x "$repackcode" ] ; then
+                load_helper epm-repack-rpm
+                load_helper epm-repack-deb
+                __epm_repack_to_rpm "$@" || return
+                [ -n "$repacked_pkgs" ] || return
+                __epm_repack_to_deb $repacked_pkgs
+            else
+                load_helper epm-repack-deb
+                __epm_repack_to_deb "$@" || return
+            fi
+            ;;
+        *)
+            fatal "$PKGFORMAT is not supported for repack yet"
+            ;;
+    esac
 
-	return 0
+    return 0
 }
 
 __epm_repack_if_needed()
 {
-	# return 1 if there is a package in host package format
-	__epm_split_by_pkg_type $PKGFORMAT "$@" && return 1
+    # return 1 if there is a package in host package format
+    __epm_split_by_pkg_type $PKGFORMAT "$@" && return 1
 
-	__epm_repack "$@"
-	return 0
+    __epm_repack "$@"
+    return 0
 }
 
 epm_repack()
@@ -242,7 +242,7 @@ epm_repack()
             echo
             echo "Adapted packages:"
             for i in $repacked_pkgs ; do
-                echo "	$EPMCURDIR/$(basename "$i")"
+                echo "    $EPMCURDIR/$(basename "$i")"
             done
         fi
     fi
diff --git a/bin/epm-repopkg b/bin/epm-repopkg
--- a/bin/epm-repopkg
+++ b/bin/epm-repopkg
@@ -21,73 +21,73 @@ load_helper epm-sh-altlinux
 
 __epm_repo_pkgadd_alt()
 {
-	local archlist="i586 x86_64 aarch64 noarch"
+    local archlist="i586 x86_64 aarch64 noarch"
 
-	local REPO_DIR="$1"
-	shift
-	[ -d "$REPO_DIR" ] || fatal "Can't find repo dir $REPO_DIR."
+    local REPO_DIR="$1"
+    shift
+    [ -d "$REPO_DIR" ] || fatal "Can't find repo dir $REPO_DIR."
 
-	# default name
-	REPO_NAME="addon"
-	# detect if already exists
-	for arch in $archlist ; do
-		local rd="$(echo $REPO_DIR/$arch/RPMS.*)"
-		[ -d "$rd" ] && REPO_NAME="$(echo "$rd" | sed -e 's|.*\.||')" && break
-	done
+    # default name
+    REPO_NAME="addon"
+    # detect if already exists
+    for arch in $archlist ; do
+        local rd="$(echo $REPO_DIR/$arch/RPMS.*)"
+        [ -d "$rd" ] && REPO_NAME="$(echo "$rd" | sed -e 's|.*\.||')" && break
+    done
 
-	[ -n "$1" ] || fatal "Missed package name"
+    [ -n "$1" ] || fatal "Missed package name"
 
-	while [ -s "$1" ] ; do
-		arch="$(epm print arch from filename "$1")" || fatal
-		epm checkpkg "$1" || fatal
-		cp -v "$1" $REPO_DIR/$arch/RPMS.$REPO_NAME || fatal
-		shift
-	done
+    while [ -s "$1" ] ; do
+        arch="$(epm print arch from filename "$1")" || fatal
+        epm checkpkg "$1" || fatal
+        cp -v "$1" $REPO_DIR/$arch/RPMS.$REPO_NAME || fatal
+        shift
+    done
 
 }
 
 
 __epm_repo_pkgdel_alt()
 {
-	local archlist="i586 x86_64 aarch64 noarch"
+    local archlist="i586 x86_64 aarch64 noarch"
 
-	local REPO_DIR="$1"
-	shift
-	[ -d "$REPO_DIR" ] || fatal "Can't find repo dir $REPO_DIR."
+    local REPO_DIR="$1"
+    shift
+    [ -d "$REPO_DIR" ] || fatal "Can't find repo dir $REPO_DIR."
 
-	[ -n "$1" ] || fatal "Missed package name"
+    [ -n "$1" ] || fatal "Missed package name"
 
-	# default name
-	REPO_NAME="addon"
-	# detect if already exists
-	for arch in $archlist ; do
-		local rd="$(echo $REPO_DIR/$arch/RPMS.*)"
-		[ -d "$rd" ] && REPO_NAME="$(echo "$rd" | sed -e 's|.*\.||')" && break
-	done
+    # default name
+    REPO_NAME="addon"
+    # detect if already exists
+    for arch in $archlist ; do
+        local rd="$(echo $REPO_DIR/$arch/RPMS.*)"
+        [ -d "$rd" ] && REPO_NAME="$(echo "$rd" | sed -e 's|.*\.||')" && break
+    done
 
-	while [ -s "$1" ] ; do
-		for arch in $archlist ; do
-			local rd="$REPO_DIR/$arch/RPMS.$REPO_NAME"
-			for i in $rd/$1* ; do
-				[ "$1" = "$(epm print name for package $i)" || continue
-				rm -v $rd/$1*
-			done
-		done
-		shift
-	done
+    while [ -s "$1" ] ; do
+        for arch in $archlist ; do
+            local rd="$REPO_DIR/$arch/RPMS.$REPO_NAME"
+            for i in $rd/$1* ; do
+                [ "$1" = "$(epm print name for package $i)" || continue
+                rm -v $rd/$1*
+            done
+        done
+        shift
+    done
 
 }
 
 
 __epm_repo_pkgupdate_alt()
 {
-	local dir="$1"
-	shift
-	for i in "$@" ; do
-		pkg="$(epm print name for package $i)" || fatal
-		__epm_repo_pkgdel_alt "$dir" $pkg
-	done
-	__epm_repo_pkgadd_alt "$dir" "$@"
+    local dir="$1"
+    shift
+    for i in "$@" ; do
+        pkg="$(epm print name for package $i)" || fatal
+        __epm_repo_pkgdel_alt "$dir" $pkg
+    done
+    __epm_repo_pkgadd_alt "$dir" "$@"
 }
 
 
@@ -96,12 +96,12 @@ epm_repo_pkgadd()
 {
 
 case $PMTYPE in
-	apt-rpm)
-		__epm_repo_pkgadd_alt "$@"
-		;;
-	*)
-		fatal "Have no suitable command for $PMTYPE"
-		;;
+    apt-rpm)
+        __epm_repo_pkgadd_alt "$@"
+        ;;
+    *)
+        fatal "Have no suitable command for $PMTYPE"
+        ;;
 esac
 
 }
@@ -111,12 +111,12 @@ epm_repo_pkgupdate()
 {
 
 case $PMTYPE in
-	apt-rpm)
-		__epm_repo_pkgupdate_alt "$@"
-		;;
-	*)
-		fatal "Have no suitable command for $PMTYPE"
-		;;
+    apt-rpm)
+        __epm_repo_pkgupdate_alt "$@"
+        ;;
+    *)
+        fatal "Have no suitable command for $PMTYPE"
+        ;;
 esac
 
 }
@@ -126,12 +126,12 @@ epm_repo_pkgdel()
 {
 
 case $PMTYPE in
-	apt-rpm)
-		__epm_repo_pkgdel_alt "$@"
-		;;
-	*)
-		fatal "Have no suitable command for $PMTYPE"
-		;;
+    apt-rpm)
+        __epm_repo_pkgdel_alt "$@"
+        ;;
+    *)
+        fatal "Have no suitable command for $PMTYPE"
+        ;;
 esac
 
 }
diff --git a/bin/epm-reposave b/bin/epm-reposave
--- a/bin/epm-reposave
+++ b/bin/epm-reposave
@@ -24,54 +24,54 @@ load_helper epm-sh-altlinux
 SAVELISTDIR=/tmp/eepm-etc-save
 __save_alt_repo_lists()
 {
-	assure_root
-	info "Creating copy of all sources lists to $SAVELISTDIR ..."
-	local i
-	rm -rf $verbose $SAVELISTDIR 2>/dev/null
-	mkdir -p $SAVELISTDIR/apt/ $SAVELISTDIR/apt/sources.list.d/
-	for i in /etc/apt/sources.list /etc/apt/sources.list.d/*.list ; do
-		[ -s "$i" ] || continue
-		local DD="$(echo "$i" | sed -e "s|/etc|$SAVELISTDIR|")"
-		cp -af $verbose "$i" "$DD" || fatal "Can't save apt source list files to $SAVELISTDIR"
-	done
+    assure_root
+    info "Creating copy of all sources lists to $SAVELISTDIR ..."
+    local i
+    rm -rf $verbose $SAVELISTDIR 2>/dev/null
+    mkdir -p $SAVELISTDIR/apt/ $SAVELISTDIR/apt/sources.list.d/
+    for i in /etc/apt/sources.list /etc/apt/sources.list.d/*.list ; do
+        [ -s "$i" ] || continue
+        local DD="$(echo "$i" | sed -e "s|/etc|$SAVELISTDIR|")"
+        cp -af $verbose "$i" "$DD" || fatal "Can't save apt source list files to $SAVELISTDIR"
+    done
 }
 
 # under root only
 __restore_alt_repo_lists()
 {
-	assure_root
-	info "Restoring copy of all sources lists from $SAVELISTDIR ..."
-	local i
-	[ -d "$SAVELISTDIR/apt" ] || return 0
-	mkdir -p $SAVELISTDIR/apt/ $SAVELISTDIR/apt/sources.list.d/
-	for i in /etc/apt/sources.list /etc/apt/sources.list.d/*.list ; do
-		[ -s "$i" ] || continue
-		local DD="$(echo "$i" | sed -e "s|/etc|$SAVELISTDIR|")"
-		# restore only if there are differences
-		if diff -q "$DD" "$i" >/dev/null ; then
-			rm -f $verbose "$DD"
-		else
-			mv $verbose "$DD" "$i" || warning "Can't restore $i file"
-		fi
-	done
+    assure_root
+    info "Restoring copy of all sources lists from $SAVELISTDIR ..."
+    local i
+    [ -d "$SAVELISTDIR/apt" ] || return 0
+    mkdir -p $SAVELISTDIR/apt/ $SAVELISTDIR/apt/sources.list.d/
+    for i in /etc/apt/sources.list /etc/apt/sources.list.d/*.list ; do
+        [ -s "$i" ] || continue
+        local DD="$(echo "$i" | sed -e "s|/etc|$SAVELISTDIR|")"
+        # restore only if there are differences
+        if diff -q "$DD" "$i" >/dev/null ; then
+            rm -f $verbose "$DD"
+        else
+            mv $verbose "$DD" "$i" || warning "Can't restore $i file"
+        fi
+    done
 }
 
 # save and restore repo lists
 __on_error_restore_alt_repo_lists()
 {
-	warning "An error occurred..."
-	epm repo restore
+    warning "An error occurred..."
+    epm repo restore
 }
 
 try_change_alt_repo()
 {
-	epm repo save
-	trap __on_error_restore_alt_repo_lists EXIT
+    epm repo save
+    trap __on_error_restore_alt_repo_lists EXIT
 }
 
 end_change_alt_repo()
 {
-	trap - EXIT
+    trap - EXIT
 }
 
 
@@ -79,16 +79,16 @@ end_change_alt_repo()
 epm_reposave()
 {
 case $PMTYPE in
-	apt-*)
-		if ! is_root ; then
-			sudoepm repo save
-			return
-		fi
-		__save_alt_repo_lists
-		;;
-	*)
-		fatal "Have no suitable command for $PMTYPE"
-		;;
+    apt-*)
+        if ! is_root ; then
+            sudoepm repo save
+            return
+        fi
+        __save_alt_repo_lists
+        ;;
+    *)
+        fatal "Have no suitable command for $PMTYPE"
+        ;;
 esac
 
 }
@@ -96,16 +96,16 @@ esac
 epm_reporestore()
 {
 case $PMTYPE in
-	apt-*)
-		if ! is_root ; then
-			sudoepm repo restore
-			return
-		fi
-		__restore_alt_repo_lists
-		;;
-	*)
-		fatal "Have no suitable command for $PMTYPE"
-		;;
+    apt-*)
+        if ! is_root ; then
+            sudoepm repo restore
+            return
+        fi
+        __restore_alt_repo_lists
+        ;;
+    *)
+        fatal "Have no suitable command for $PMTYPE"
+        ;;
 esac
 
 }
@@ -113,12 +113,12 @@ esac
 epm_reporeset()
 {
 case $PMTYPE in
-	winget)
-		sudocmd winget source reset
-		;;
-	*)
-		fatal "Have no suitable command for $PMTYPE"
-		;;
+    winget)
+        sudocmd winget source reset
+        ;;
+    *)
+        fatal "Have no suitable command for $PMTYPE"
+        ;;
 esac
 
 }
diff --git a/bin/epm-site b/bin/epm-site
--- a/bin/epm-site
+++ b/bin/epm-site
@@ -24,105 +24,105 @@ PAOURL="https://packages.altlinux.org"
 
 paoapi()
 {
-	# http://petstore.swagger.io/?url=http://packages.altlinux.org/api/docs
-	assure_exists curl || return 1
-	showcmd curl "$PAOURL/api/$1"
-	a='' curl -s --header "Accept: application/json" "$PAOURL/api/$1"
+    # http://petstore.swagger.io/?url=http://packages.altlinux.org/api/docs
+    assure_exists curl || return 1
+    showcmd curl "$PAOURL/api/$1"
+    a='' curl -s --header "Accept: application/json" "$PAOURL/api/$1"
 }
 
 # TODO: use /home/lav/Projects/git/JSON.sh
 get_pao_var()
 {
-	local FIELD="$1"
-	#grep '"$FIELD"' | sed -e 's|.*"$FIELD":"||g' | sed -e 's|".*||g'
-	$SHAREDIR/tools_json -b | grep -E "\[.*\"$FIELD\"\]" | sed -e 's|.*[[:space:]]"\(.*\)"|\1|g'
-	return 0
+    local FIELD="$1"
+    #grep '"$FIELD"' | sed -e 's|.*"$FIELD":"||g' | sed -e 's|".*||g'
+    $SHAREDIR/tools_json -b | grep -E "\[.*\"$FIELD\"\]" | sed -e 's|.*[[:space:]]"\(.*\)"|\1|g'
+    return 0
 }
 
 
 run_command_if_exists()
 {
-	local CMD="$1"
-	shift
-	if is_command "$CMD" ; then
-		docmd $CMD "$@"
-		return 0
-	fi
-	return 1
+    local CMD="$1"
+    shift
+    if is_command "$CMD" ; then
+        docmd $CMD "$@"
+        return 0
+    fi
+    return 1
 }
 
 # TODO: use something like xdg-browser
 open_browser()
 {
-	local i
-	for i in xdg-open firefox chromium links ; do
-		run_command_if_exists $i "$@" && return
-	done
+    local i
+    for i in xdg-open firefox chromium links ; do
+        run_command_if_exists $i "$@" && return
+    done
 }
 
 __query_package_hl_url()
 {
-	case $DISTRNAME in
-		ALTLinux|ALTServer)
-			paoapi srpms/$1 | get_pao_var url
-			;;
-	esac
-	return 1
+    case $DISTRNAME in
+        ALTLinux|ALTServer)
+            paoapi srpms/$1 | get_pao_var url
+            ;;
+    esac
+    return 1
 }
 
 query_package_url()
 {
-	local URL
+    local URL
 
-	case $PMTYPE in
-		*-rpm)
-			# TODO: for binary packages?
-			query_package_field URL "$1" || __query_package_hl_url "$1"
-			#LANG=C epm info "$1"
-			return
-			;;
-		homebrew)
-			docmd brew "$1" | grep "^From: " | sed -e "s|^From: ||"
-			return
-			;;
-	esac
-	fatal "rpm based distro supported only. TODO: Realize via web service?"
+    case $PMTYPE in
+        *-rpm)
+            # TODO: for binary packages?
+            query_package_field URL "$1" || __query_package_hl_url "$1"
+            #LANG=C epm info "$1"
+            return
+            ;;
+        homebrew)
+            docmd brew "$1" | grep "^From: " | sed -e "s|^From: ||"
+            return
+            ;;
+    esac
+    fatal "rpm based distro supported only. TODO: Realize via web service?"
 }
 
 get_locale()
 {
-	local loc
-	loc=$(a='' natspec --locale 2>/dev/null)
-	[ -n "$loc" ] || loc=$LANG
-	echo $loc
+    local loc
+    loc=$(a='' natspec --locale 2>/dev/null)
+    [ -n "$loc" ] || loc=$LANG
+    echo $loc
 }
 
 get_pao_url()
 {
-	local loc
-	loc=$(get_locale | cut -c1-2)
-	case $loc in
-		en|ru|uk|br)
-			loc=$loc
-			;;
-		*)
-			loc=en
-	esac
-	echo "$PAOURL/$loc/Sisyphus/srpms"
+    local loc
+    loc=$(get_locale | cut -c1-2)
+    case $loc in
+        en|ru|uk|br)
+            loc=$loc
+            ;;
+        *)
+            loc=en
+    esac
+    echo "$PAOURL/$loc/Sisyphus/srpms"
 }
 
 query_altlinux_url()
 {
-	local URL
-	case $PMTYPE in
-		*-rpm)
-			local srpm=$(print_srcname "$1")
-			[ -n "$srpm" ] || fatal "Can't get source name for $1"
-			echo "$(get_pao_url)/$srpm"
-			return
-			;;
-	esac
-	fatal "rpm based distro supported only. TODO: Realize via web service?"
+    local URL
+    case $PMTYPE in
+        *-rpm)
+            local srpm=$(print_srcname "$1")
+            [ -n "$srpm" ] || fatal "Can't get source name for $1"
+            echo "$(get_pao_url)/$srpm"
+            return
+            ;;
+    esac
+    fatal "rpm based distro supported only. TODO: Realize via web service?"
 }
 
 epm_site()
@@ -132,18 +132,18 @@ epm_site()
 
 local PAO=""
 for f in $pkg_names $pkg_files ; do
-	[ "$f" = "-p" ] && PAO="$f" && continue
-	if [ -n "$PAO" ] ; then
-		pkg_url=$(query_altlinux_url $f)
-	else
-		pkg_url=$(query_package_url $f)
-	fi
-	[ -n "$pkg_url" ] && open_browser "$pkg_url" && continue
-	warning "Can't get URL for $f package"
+    [ "$f" = "-p" ] && PAO="$f" && continue
+    if [ -n "$PAO" ] ; then
+        pkg_url=$(query_altlinux_url $f)
+    else
+        pkg_url=$(query_package_url $f)
+    fi
+    [ -n "$pkg_url" ] && open_browser "$pkg_url" && continue
+    warning "Can't get URL for $f package"
 done
 
 #for f in $pkg_names ; do
-#	LANG=C epm info $f
+#    LANG=C epm info $f
 #done
 
 # TODO: -p for p.a.o (see rpmurl)
diff --git a/bin/epm-upgrade b/bin/epm-upgrade
--- a/bin/epm-upgrade
+++ b/bin/epm-upgrade
@@ -22,157 +22,160 @@ load_helper epm-sh-warmup
 
 epm_upgrade()
 {
-	local CMD
+    local CMD
 
-	# it is useful for first time running
-	update_repo_if_needed
+    # it is useful for first time running
+    update_repo_if_needed
 
-	warmup_bases
+    warmup_bases
 
-	if [ "$BASEDISTRNAME" = "alt" ] ; then
-		load_helper epm-sh-altlinux
-		if tasknumber "$@" >/dev/null ; then
-			load_helper epm-addrepo
-			load_helper epm-reposave
-			load_helper epm-removerepo
-			load_helper epm-Install
+    if [ "$BASEDISTRNAME" = "alt" ] ; then
+        load_helper epm-sh-altlinux
+        if tasknumber "$@" >/dev/null ; then
+            load_helper epm-addrepo
+            load_helper epm-reposave
+            load_helper epm-removerepo
+            load_helper epm-Install
 
-			local installlist="$(get_task_packages $*)"
-			# hack: drop -devel packages to avoid package provided by multiple packages
-			installlist="$(estrlist reg_exclude ".*-devel .*-devel-static" "$installlist")"
-			[ -n "$verbose" ] && info "Packages from task(s): $installlist"
-			# install only installed packages (simulate upgrade packages)
-			installlist="$(get_only_installed_packages "$installlist")"
-			[ -n "$verbose" ] && info "Packages to upgrade: $installlist"
-			if [ -z "$installlist" ] ; then
-				warning "There is no installed packages for upgrade from task $*"
-				return 22
-			fi
+            local installlist="$(get_task_packages $*)"
+            # hack: drop -devel packages to avoid package provided by multiple packages
+            installlist="$(estrlist reg_exclude ".*-devel .*-devel-static" "$installlist")"
+            [ -n "$verbose" ] && info "Packages from task(s): $installlist"
+            # install only installed packages (simulate upgrade packages)
+            installlist="$(get_only_installed_packages "$installlist")"
+            [ -n "$verbose" ] && info "Packages to upgrade: $installlist"
+            if [ -z "$installlist" ] ; then
+                warning "There is no installed packages for upgrade from task $*"
+                return 22
+            fi
 
-			try_change_alt_repo
-			epm_addrepo "$@"
-			(pkg_names="$installlist" epm_Install) || fatal "Can't update repo"
-			epm_removerepo "$@"
-			end_change_alt_repo
+            try_change_alt_repo
+            epm_addrepo "$@"
+            (pkg_names="$installlist" epm_Install) || fatal "Can't update repo"
+            epm_removerepo "$@"
+            end_change_alt_repo
 
-			return
-		fi
-	fi
+            return
+        fi
+    fi
 
-	# Solus supports upgrade for a package (with all dependencies)
-	if [ -n "$1" ] && [ "$DISTRNAME" = "Solus" ] ; then
-		sudocmd eopkg upgrade "$@"
-		return
-	fi
+    # Solus supports upgrade for a package (with all dependencies)
+    if [ -n "$1" ] && [ "$DISTRNAME" = "Solus" ] ; then
+        sudocmd eopkg upgrade "$@"
+        return
+    fi
 
-	info "Running command for upgrade packages"
+    info "Running command for upgrade packages"
 
-	case $PMTYPE in
-		*-rpm)
-			# upgrade only install files from the list
-			if [ -n "$pkg_files" ] ; then
-				load_helper epm-install
-				#sudocmd rpm -Fvh $pkg_files
-				(pkg_files=$pkg_files force="$force -F" epm_install)
-				return
-			elif [ -n "$pkg_names" ] ; then
-				# hack for https://bugzilla.altlinux.org/41225
-				case "$pkg_names" in
-					-*)
-						fatal "Option $pkg_names is not allowed here"
-				esac
-				load_helper epm-install
-				(pkg_names=$(get_only_installed_packages $pkg_names) epm_install)
-				return
-			fi
-		;;
-	esac
+    case $PMTYPE in
+        *-rpm)
+            # upgrade only install files from the list
+            if [ -n "$pkg_files" ] ; then
+                load_helper epm-install
+                #sudocmd rpm -Fvh $pkg_files
+                (pkg_files=$pkg_files force="$force -F" epm_install)
+                return
+            elif [ -n "$pkg_names" ] ; then
+                # hack for https://bugzilla.altlinux.org/41225
+                case "$pkg_names" in
+                    -*)
+                        fatal "Option $pkg_names is not allowed here"
+                esac
+                load_helper epm-install
+                (pkg_names=$(get_only_installed_packages $pkg_names) epm_install)
+                return
+            fi
+        ;;
+    esac
 
-	case $PMTYPE in
-	apt-rpm|apt-dpkg)
-		local APTOPTIONS="$(subst_option non_interactive -y) $(subst_option verbose "-o Debug::pkgMarkInstall=1 -o Debug::pkgProblemResolver=1")"
-		CMD="apt-get $APTOPTIONS $noremove $force_yes dist-upgrade"
-		;;
-	aptitude-dpkg)
-		CMD="aptitude dist-upgrade"
-		;;
-	packagekit)
-		docmd pkcon update
-		return
-		;;
-	yum-rpm)
-		local OPTIONS="$(subst_option non_interactive -y)"
-		# can do update repobase automagically
-		CMD="yum $OPTIONS update $*"
-		;;
-	dnf-rpm)
-		local OPTIONS="$(subst_option non_interactive -y)"
-		CMD="dnf $OPTIONS distro-sync $*"
-		;;
-	snappy)
-		CMD="snappy update"
-		;;
-	urpm-rpm)
-		# or --auto-select --replace-files
-		CMD="urpmi --update --auto-select $*"
-		;;
-	zypper-rpm)
-		CMD="zypper $(subst_option non_interactive --non-interactive) dist-upgrade"
-		;;
-	pacman)
-		CMD="pacman -S -u $force"
-		;;
-	aura)
-		CMD="aura -A -u"
-		;;
-	emerge)
-		CMD="emerge -NuDa world"
-		;;
-	conary)
-		CMD="conary updateall"
-		;;
-	pkgsrc)
-		CMD="freebsd-update fetch install"
-		;;
-	pkgng)
-		CMD="pkg upgrade"
-		;;
-	chocolatey)
-		CMD="chocolatey update all"
-		;;
-	homebrew)
-		#CMD="brew upgrade"
-		docmd brew upgrade $(brew outdated)
-		return
-		;;
-	opkg)
-		CMD="opkg upgrade"
-		;;
-	eopkg)
-		CMD="eopkg upgrade"
-		;;
-	slackpkg)
-		CMD="/usr/sbin/slackpkg upgrade-all"
-		;;
-	guix)
-		CMD="guix package -u"
-		;;
-	appget|winget)
-		CMD="$PMTYPE update-all"
-		;;
-	aptcyg)
-		# shellcheck disable=SC2046
-		docmd_foreach "epm install" $(short=1 epm packages)
-		return
-		;;
-	xbps)
-		CMD="xbps-install -Su"
-		;;
-	*)
-		fatal "Have no suitable command for $PMTYPE"
-		;;
-	esac
+    case $PMTYPE in
+    apt-rpm|apt-dpkg)
+        local APTOPTIONS="$(subst_option non_interactive -y) $(subst_option verbose "-o Debug::pkgMarkInstall=1 -o Debug::pkgProblemResolver=1")"
+        CMD="apt-get $APTOPTIONS $noremove $force_yes dist-upgrade"
+        ;;
+    aptitude-dpkg)
+        CMD="aptitude dist-upgrade"
+        ;;
+    packagekit)
+        docmd pkcon update
+        return
+        ;;
+    yum-rpm)
+        local OPTIONS="$(subst_option non_interactive -y)"
+        # can do update repobase automagically
+        CMD="yum $OPTIONS update $*"
+        ;;
+    dnf-rpm)
+        local OPTIONS="$(subst_option non_interactive -y)"
+        CMD="dnf $OPTIONS distro-sync $*"
+        ;;
+    snappy)
+        CMD="snappy update"
+        ;;
+    urpm-rpm)
+        # or --auto-select --replace-files
+        CMD="urpmi --update --auto-select $*"
+        ;;
+    zypper-rpm)
+        CMD="zypper $(subst_option non_interactive --non-interactive) dist-upgrade"
+        ;;
+    pacman)
+        CMD="pacman -S -u $force"
+        ;;
+    aura)
+        CMD="aura -A -u"
+        ;;
+    emerge)
+        CMD="emerge -NuDa world"
+        ;;
+    conary)
+        CMD="conary updateall"
+        ;;
+    pkgsrc)
+        CMD="freebsd-update fetch install"
+        ;;
+    pkgng)
+        CMD="pkg upgrade"
+        ;;
+    apk)
+        CMD="apk upgrade"
+        ;;
+    chocolatey)
+        CMD="chocolatey update all"
+        ;;
+    homebrew)
+        #CMD="brew upgrade"
+        docmd brew upgrade $(brew outdated)
+        return
+        ;;
+    opkg)
+        CMD="opkg upgrade"
+        ;;
+    eopkg)
+        CMD="eopkg upgrade"
+        ;;
+    slackpkg)
+        CMD="/usr/sbin/slackpkg upgrade-all"
+        ;;
+    guix)
+        CMD="guix package -u"
+        ;;
+    appget|winget)
+        CMD="$PMTYPE update-all"
+        ;;
+    aptcyg)
+        # shellcheck disable=SC2046
+        docmd_foreach "epm install" $(short=1 epm packages)
+        return
+        ;;
+    xbps)
+        CMD="xbps-install -Su"
+        ;;
+    *)
+        fatal "Have no suitable command for $PMTYPE"
+        ;;
+    esac
 
-	sudocmd $CMD "$@"
+    sudocmd $CMD "$@"
 
 }
