epm install: add --repack support (binary rpm repacking before install)

diff --git a/bin/epm-install b/bin/epm-install
--- a/bin/epm-install
+++ b/bin/epm-install
@@ -351,6 +351,77 @@ __epm_check_if_try_install_rpm()
 	return 0
 }
 
+# args: buildroot spec
+__fix_spec()
+{
+    local buildroot="$1"
+    local spec="$2"
+    local i
+    for i in $(grep '^"/' $spec | sed -e 's|^"\(.*\)"$|\1|') ; do
+        #' hack for highlight
+        # add %dir to dir in list
+        if [ -d "$buildroot$i" ] ; then
+            subst 's|^\("'$i'"\)$|%dir \1|' $spec
+        fi
+    done
+    subst "s|^Release: |Release: alt1.repacked.with.epm.|" $spec
+    subst "s|^\((Converted from a rpm package.*\)|(Repacked from binary rpm with epm $EPMVERSION)\n\1|" $spec
+    #" hack for highlight
+}
+
+# will fill repacked_rpms var
+__epm_repack_rpm()
+{
+    [ "$DISTRNAME" = "ALTLinux" ] || fatal "install --repack supported only for ALT Linux distros"
+
+    assure_exists fakeroot || fatal
+    assure_exists alien || fatal
+    assure_exists rpmbuild rpm-build || fatal
+
+    local pkg
+    local tmpbuilddir=$(mktemp -d)/repack
+    mkdir $tmpbuilddir
+
+    local abspkg
+    repacked_rpms=''
+    for pkg in $* ; do
+        abspkg=$(realpath $pkg)
+        info "Repacking $abspkg to local rpm format ..."
+        cd $tmpbuilddir || fatal
+        docmd fakeroot alien --generate --to-rpm $verbose $scripts $abspkg || fatal
+
+        local subdir="$(echo *)"
+        [ -d "$subdir" ] || fatal "can't find subdir"
+
+        # detect spec and move to prev dir
+        local spec="$(echo $tmpbuilddir/$subdir/*.spec)"
+        [ -s "$spec" ] || fatal "can't find spec"
+        mv $spec $tmpbuilddir || fatal
+        spec="$tmpbuilddir/$(basename "$spec")"
+        __fix_spec $tmpbuilddir/$subdir $spec
+        showcmd fakeroot rpmbuild --buildroot $tmpbuilddir/$subdir --define='_allow_root_build 1' -bb $spec
+        if [ -n "$verbose" ] ; then
+            fakeroot rpmbuild --buildroot $tmpbuilddir/$subdir --define='_allow_root_build 1' -bb $spec || fatal
+        else
+            fakeroot rpmbuild --buildroot $tmpbuilddir/$subdir --define='_allow_root_build 1' -bb $spec >/dev/null || fatal
+        fi
+        local repacked_rpm="$(realpath $tmpbuilddir/../*.rpm)"
+        if [ -s "$repacked_rpm" ] ; then
+            repacked_rpms="$repacked_rpms $repacked_rpm"
+            to_remove_pkg_files="$to_remove_pkg_files $repacked_rpm"
+        else
+            warning "Can't find converted rpm for source binary $pkg package"
+        fi
+        cd - >/dev/null
+        rm -rf $tmpbuilddir/$subdir/
+        #rm -rf $tmpbuilddir/../*.rpm
+        rm -rf $spec
+    done
+    rmdir $tmpbuilddir
+    #rmdir $tmpbuilddir/..
+    true
+}
+
 __handle_direct_install()
 {
     case "$DISTRNAME" in
@@ -610,11 +681,11 @@ epm_install()
         return
     fi
 
-    if [ -n "$direct" ] ; then
+    if [ -n "$direct" ] || [ -n "$repack" ] ; then
         __handle_direct_install
     fi
 
-    # if possible, it will put pkg_urls into pkg_files or pkg_names
+    # if possible, it will put pkg_urls into pkg_files and reconstruct pkg_filenames
     if [ -n "$pkg_urls" ] ; then
         load_helper epm-download
         __handle_pkg_urls_to_install
@@ -642,6 +713,13 @@ epm_install()
     fi
 
     epm_install_names $names || return
+
+    # repack binary files
+    if [ -n "$repack" ] ; then
+        __epm_repack_rpm $files || fatal
+        files="$repacked_rpms"
+    fi
+
     epm_install_files $files
     local RETVAL=$?
 
