epm ei: improve checking for url(s) returned from Korinf repo

diff --git a/bin/epm-epm_install b/bin/epm-epm_install
--- a/bin/epm-epm_install
+++ b/bin/epm-epm_install
@@ -48,10 +48,12 @@ __epm_korinf_list() {
 
 __epm_korinf_install() {
 
-    local pkg
+    local pkg pkgurl
     local pkg_urls=''
-    for pkg in $* ; do
-        pkg_urls="$pkg_urls $(__epm_korinf_site_mask "$pkg")"
+    for pkgurl in $* ; do
+        pkg="$(__epm_korinf_site_mask "$pkgurl")"
+        [ -n "$pkg" ] || fatal "Can't get package url from $pkgurl"
+        [ -n "$pkg_urls" ] && pkg_urls="$pkg_urls $pkg" || pkg_urls="$pkg"
     done
     # due Error: Can't use epm call from the piped script
     #epm install $(__epm_korinf_site_mask "$PACKAGE")
