epm-assure: improve version checking

diff --git a/bin/epm-sh-functions b/bin/epm-sh-functions
--- a/bin/epm-sh-functions
+++ b/bin/epm-sh-functions
@@ -336,8 +336,10 @@ assure_exists()
 {
 	load_helper epm-assure
 	local package="$2"
+	local textpackage=
 	[ -n "$package" ] || package="$(__get_package_for_command "$1")"
-	__epm_assure "$1" $package $3 || fatal "Can't assure in '$1' command"
+	[ -n "$3" ] && textpackage=" >= $3"
+	__epm_assure "$1" $package $3 || fatal "Can't assure in '$1' command from $package$textpackage package"
 }
 
 eget()
