some checkbashisms fixes

diff --git a/bin/epm-download b/bin/epm-download
--- a/bin/epm-download
+++ b/bin/epm-download
@@ -67,7 +67,7 @@ __download_pkg_urls()
     local url
     [ -z "$pkg_urls" ] && return
     for url in $pkg_urls ; do
-        local tmppkg=$(mktemp -d) || fatal "failed mktemp -d"
+        local tmppkg="$(mktemp -d)" || fatal "failed mktemp -d"
         docmd chmod $verbose a+rX $tmppkg
         showcmd cd $tmppkg
         cd $tmppkg || fatal
@@ -157,7 +157,7 @@ __epm_print_url_alt_check()
 {
     local pkg=$1
     shift
-    local tm=$(mktemp)
+    local tm="$(mktemp)"
     assure_exists curl
     load_helper epm-site
     quiet=1
