epm-release_upgrade: improvements for p11

diff --git a/bin/epm-release_upgrade b/bin/epm-release_upgrade
--- a/bin/epm-release_upgrade
+++ b/bin/epm-release_upgrade
@@ -82,6 +82,9 @@ __p11_upgrade_fix()
         info "Need to install default apt-conf package to avoid missing $TO repo"
         docmd epm install apt-conf-branch || fatal
     fi
+    # файл /etc/openssl/openssl.cnf из устанавливаемого пакета openssl-config-3.2.0-alt1.noarch конфликтует с файлом из пакета libcrypto10-1.0.2u-alt1.p9.2.x86_64
+    docmd epm remove libcrypto10 libssl10
+
     # libcrypto1.1 fix
     docmd epm repo save
     docmd epm repo rm all
@@ -218,6 +221,7 @@ __check_system()
             warning 'Current distro still is not $TO, or altlinux-release-sisyphus package is installed.'
             warning 'Trying to fix with altlinux-release-$TO'
             docmd epm install altlinux-release-$TO
+            docmd epm install altlinux-os-release
         fi
     fi
 
@@ -371,7 +375,7 @@ __switch_alt_to_distro()
             docmd epm update-kernel || fatal
             info "Run epm release-upgrade again for update to p10"
             ;;
-        "p9"|"p9 p10"|"p10 p10"|"p10 p11")
+        "p9"|"p9 p10"|"p10 p10")
             info "Upgrade all packages to current $FROM repository"
             __do_upgrade
             confirm_info "Upgrade $DISTRNAME from $FROM to $TO ..."
@@ -383,6 +387,20 @@ __switch_alt_to_distro()
             docmd epm install rpm apt $(get_fix_release_pkg "$TO") || fatal "Check the errors and run '# epm release-upgrade' again"
             __check_system "$TO"
             docmd epm update-kernel -t std-def || fatal
+            ;;
+        "p10 p11")
+            info "Upgrade all packages to current $FROM repository"
+            __do_upgrade
+            confirm_info "Upgrade $DISTRNAME from $FROM to $TO ..."
+            docmd epm install rpm apt $(get_fix_release_pkg "$FROM") || fatal
+            __p11_upgrade_fix
+            __switch_repo_to $TO
+            end_change_alt_repo
+            __do_upgrade
+            docmd epm install rpm apt $(get_fix_release_pkg "$TO") || fatal "Check the errors and run '# epm release-upgrade' again"
+            __check_system "$TO"
+            # will update to kernel 6.6
+            docmd epm update-kernel || fatal
             ;;
         "p9 p8"|"c8.1 c8"|"c8.1 p8"|"p8 p8")
             confirm_info "Downgrade $DISTRNAME from $FROM to $TO ..."
