epm requires: add ELF support

diff --git a/bin/epm-requires b/bin/epm-requires
--- a/bin/epm-requires
+++ b/bin/epm-requires
@@ -35,6 +35,45 @@ __epm_alt_rpm_requires()
     fi
 }
 
+get_linked_shared_libs()
+{
+    assure_exists readelf binutils
+    #is_command readelf || fatal "Can't get required shared library: readelf is missed. Try install binutils package."
+    #ldd "$exe" | sed -e 's|[[:space:]]*||' | grep "^lib.*[[:space:]]=>[[:space:]]\(/usr/lib\|/lib\)" | sed -e 's|[[:space:]].*||'
+    LANG=C readelf -d "$1" | grep "(NEEDED)" | grep "Shared library:" | sed -e 's|.*Shared library: \[||' -e 's|\]$||' | grep "^lib"
+}
+
+__epm_elf32_requires()
+{
+    get_linked_shared_libs "$1"
+}
+
+__epm_elf64_requires()
+{
+    get_linked_shared_libs "$1" | sed -e 's|$|()(64bit)|'
+}
+
+__epm_elf_requires()
+{
+    local i
+    if [ -n "$direct" ] ; then
+        for i in $* ; do
+            get_linked_shared_libs $i
+        done
+        return
+    fi
+
+    for i in $* ; do
+        if file "$i" | grep -q " ELF 32-bit " ; then
+            __epm_elf32_requires "$i"
+        elif file "$i" | grep -q " ELF 64-bit " ; then
+            __epm_elf64_requires "$i"
+        else
+            warning "Unknown ELF binary"
+        fi
+    done
+}
+
 epm_requires_files()
 {
     local pkg_files="$*"
@@ -54,6 +93,9 @@ epm_requires_files()
         eopkg)
             showcmd eopkg info $pkg_files
             a= eopkg info $pkg_files | grep "^Dependencies" | head -n1 | sed -e "s|Dependencies[[:space:]]*: ||"
+            ;;
+        ELF)
+            __epm_elf_requires $pkg_files
             ;;
         *)
             fatal "Have no suitable command for $PKGTYPE"
