epm release-upgrade: check for glibc-core-2.17

diff --git a/bin/epm-release_upgrade b/bin/epm-release_upgrade
--- a/bin/epm-release_upgrade
+++ b/bin/epm-release_upgrade
@@ -64,7 +64,11 @@ __update_alt_repo_to_next_distro()
 			__replace_alt_version_in_repo p7 p8
 			__replace_text_in_alt_repo "/^ *#/! s!\[p7\]![updates]!g"
 			docmd epm update || fatal
-			docmd epm install apt rpm apt-conf-branch || fatal "Check an error and run epm release-upgrade again"
+			if ! docmd epm install apt rpm apt-conf-branch ; then
+				# error: execution of %post scriptlet from glibc-core-2.23-alt1.eter1
+				docmd epm erase glibc-core-2.17 || fatal "Check an error and run epm release-upgrade again"
+				docmd epm install apt rpm apt-conf-branch || fatal "Check an error and run epm release-upgrade again"
+			fi
 			__replace_text_in_alt_repo "/^ *#/! s!\[updates\]![p8]!g"
 			docmd epm update || fatal
 			if is_installed systemd && is_active_systemd systemd ; then
