fix bug with run script in epm() (fix regression from bf3b0a0d1d8fe58a0e905a2d2e4eb7a3e7a35e05)

diff --git a/bin/epm-sh-functions b/bin/epm-sh-functions
--- a/bin/epm-sh-functions
+++ b/bin/epm-sh-functions
@@ -291,8 +291,7 @@ clean_store_output()
 epm()
 {
 	if [ -n "$PROGNAME" ] ; then
-		#|| fatal "Can't use epm call from the piped script"
-		$PROGDIR/$PROGNAME --inscript "$@"
+		/bin/sh $PROGDIR/$PROGNAME --inscript "$@"
 	else
 		epm_main --inscript "$@"
 	fi
@@ -301,8 +300,8 @@ epm()
 # run $SUDO epm, possible from side repo
 sudoepm()
 {
-	[ -n "$PROGNAME" ] || fatal "Can't use epm call from the piped script"
-	sudorun $PROGDIR/$PROGNAME --inscript "$@"
+	[ -n "$PROGNAME" ] || fatal "Can't use sudo epm call from the piped script"
+	sudorun /bin/sh $PROGDIR/$PROGNAME --inscript "$@"
 }
 
 # Print error message and stop the program
