epm-release_upgrade: don't restart system-logind after install systemd-settings-disable-kill-user-processes

diff --git a/bin/epm-release_upgrade b/bin/epm-release_upgrade
--- a/bin/epm-release_upgrade
+++ b/bin/epm-release_upgrade
@@ -57,7 +57,8 @@ assure_safe_run()
 			warning "You force runnning even if systemd-logind kills screen on disconnect"
 		else
 			docmd epm install systemd-settings-disable-kill-user-processes || fatal "Can't install the package above. Fix it or run with --force."
-			docmd serv systemd-logind restart || fatal "Can't restart systemd-logind service. Fix it or run with --force."
+			# commented, will kick off the user from the system (ALT issue 50580)
+			#docmd serv systemd-logind restart || fatal "Can't restart systemd-logind service. Fix it or run with --force."
 			fatal "Now you need relogin to the system. In this session your screen still will be killed."
 		fi
 	fi
