separate code for play command

diff --git a/bin/epm-play b/bin/epm-play
--- a/bin/epm-play
+++ b/bin/epm-play
@@ -20,15 +20,42 @@
 # TODO
 epm_vardir=/var/lib/eepm
 
+__save_installed_app()
+{
+	[ -d "$epm_vardir" ] || return 0
+	estrlist list "$@" | $SUDO tee $epm_vardir/installed-app >/dev/null
+}
 
-__epm_prescription_run()
+__remove_installed_app()
+{
+	[ -d "$epm_vardir" ] || return 0
+	local i
+	for i in $* ; do
+		$SUDO sed -i "/^$i$/d" $epm_vardir/installed-app
+	done
+	return 0
+}
+
+__check_installed_app()
+{
+	[ -s $epm_vardir/installed-app ] || return 1
+	grep -q -- "^$1\$" $epm_vardir/installed-app
+}
+
+__list_installed_app()
+{
+    cat $epm_vardir/installed-app 2>/dev/null
+}
+
+
+__epm_play_run()
 {
     local script="$psdir/$1.sh"
     shift
     local option="$1"
 
     if [ ! -x "$script" ] ; then
-        fatal "Can't find $script prescription."
+        fatal "Can't find play script $script."
     fi
 
     # allow use EGET in the scripts
@@ -40,18 +67,27 @@ __epm_prescription_run()
     docmd $script $option
 }
 
-epm_prescription()
+epm_play()
 {
-
+# TODO: change to play.d
 local psdir="$CONFIGDIR/prescription.d"
 
 if [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then
     cat <<EOF
 Options:
     APP            - install APP
+    --remove APP   - remove APP
     --list         - list all installed apps
     --list-all     - list all available apps
 EOF
+    exit
+fi
+
+if [ "$1" = "--remove" ] ; then
+    shift
+    #__check_installed_app "$1" || fatal "$1 is not installed"
+    __epm_play_run $1 --remove
+    __remove_installed_app "$@"
     exit
 fi
 
@@ -66,14 +102,15 @@ if [ "$1" = "--list" ] || [ "$1" = "--installed" ] ; then
 fi
 
 if [ "$1" == "--list-all" ] || [ -z "$*" ] ; then
-    echo "Run with a name of a prescription to run:"
+    echo "Run with a name of a play script to run:"
     for i in $psdir/*.sh ; do
         printf "  %-20s - %s\n" "$(basename $i .sh)" "$($i --description 2>/dev/null)"
     done
     echo
-    echo "run epm prescription --list to list installed only"
+    echo "run epm play --list to list installed only or --remove to remove one"
     exit
 fi
 
-__epm_prescription_run "$1" --run
+__check_installed_app "$1" && info "$1 is already installed" && exit 1
+__epm_play_run "$1" --run && __save_installed_app "$1"
 }
