epm prescription: implement via epm play functions

diff --git a/bin/epm-prescription b/bin/epm-prescription
--- a/bin/epm-prescription
+++ b/bin/epm-prescription
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
-# Copyright (C) 2015, 2017, 2019, 2020  Etersoft
-# Copyright (C) 2015, 2017, 2019, 2020  Vitaly Lipatov <lav@etersoft.ru>
+# Copyright (C) 2015, 2017, 2019, 2020, 2022  Etersoft
+# Copyright (C) 2015, 2017, 2019, 2020, 2022  Vitaly Lipatov <lav@etersoft.ru>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
@@ -17,28 +17,7 @@
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 #
 
-# TODO
-epm_vardir=/var/lib/eepm
-
-
-__epm_prescription_run()
-{
-    local script="$psdir/$1.sh"
-    shift
-    local option="$1"
-
-    if [ ! -x "$script" ] ; then
-        fatal "Can't find $script prescription."
-    fi
-
-    # allow use EGET in the scripts
-    __set_EGET
-    # also we will have DISTRVENDOR there
-    export PATH=$PROGDIR:$PATH
-
-    #info "Running $($script --description 2>/dev/null) ..."
-    docmd $script $option
-}
+load_helper epm-play
 
 epm_prescription()
 {
@@ -48,34 +27,22 @@ local psdir="$CONFIGDIR/prescription.d"
 if [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then
     cat <<EOF
 Options:
-    <receipt>      - run receipt
+    <receipt>      - run <receipt>
     --list-all     - list all available receipts
 EOF
     exit
 fi
 
-[ "$($DISTRVENDOR -a)" = "x86_64" ] && IGNOREi586='' || IGNOREi586=1
-
 if [ "$1" == "--list-all" ] || [ -z "$*" ] ; then
-    if [ -n "$short" ] ; then
-        for i in $psdir/*.sh ; do
-            local name=$(basename $i .sh)
-            [ -n "$IGNOREi586" ] && rhas "$name" "^i586-" && continue
-            rhas "$name" "^common" && continue
-            echo "$name"
-        done
-        exit
-    fi
-    echo "Run with a name of a prescription to run:"
-    for i in $psdir/*.sh ; do
-        local name=$(basename $i .sh)
-        [ -n "$IGNOREi586" ] && rhas "$name" "^i586-" && continue
-        rhas "$name" "^common" && continue
-        printf "  %-20s - %s\n" "$name" "$($i --description 2>/dev/null)"
-    done
-    echo
+    [ -n "$short" ] || [ -n "$quiet" ] || echo "Run with a name of a prescription to run:"
+    __epm_play_list $psdir
     exit
 fi
 
-__epm_prescription_run "$1" --run
+prescription="$1"
+shift
+
+__check_play_script "$prescription" || fatal "We have no idea how to play $prescription (checked in $psdir)"
+__epm_play_run "$prescription" --run "$@" || fatal "There was some error during run the script."
+
 }
