epm full-upgrade: support --force for epm play

diff --git a/bin/epm-full_upgrade b/bin/epm-full_upgrade
--- a/bin/epm-full_upgrade
+++ b/bin/epm-full_upgrade
@@ -21,9 +21,10 @@ epm_full_upgrade_help()
 {
             get_help HELPCMD $SHAREDIR/epm-full_upgrade
     cat <<EOF
-You can run with --interactive if you can skip some steps interactivelyю
+You can run with --interactive if you can skip some steps interactively.
 Also you can comment out full_upgrade parts in /etc/eepm/eepm.conf config.
 Examples:
+  epm full-upgrade [--auto]
   epm full-upgrade [--interactive]
   epm full-upgrade --no-flatpack
 EOF
@@ -103,7 +104,11 @@ confirm_action()
     confirm_action "Upgrade packages installed via epm play? [Y/n]" || full_upgrade_no_epm_play=1
     if [ -z "$full_upgrade_no_epm_play" ] ; then
         [ -n "$quiet" ] || echo
-        docmd epm $dryrun play --update all || fatal "updating of applications installed via epm play is failed."
+        if [ -n "$force" ] ; then
+            docmd epm $dryrun play || fatal "updating of applications installed via epm play is failed."
+        else
+            docmd epm $dryrun play --update all || fatal "updating of applications installed via epm play is failed."
+        fi
     fi
 
 
