epm-check: improve for yum

diff --git a/bin/epm-check b/bin/epm-check
--- a/bin/epm-check
+++ b/bin/epm-check
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
-# Copyright (C) 2012  Etersoft
-# Copyright (C) 2012  Vitaly Lipatov <lav@etersoft.ru>
+# Copyright (C) 2012-2013  Etersoft
+# Copyright (C) 2012-2013  Vitaly Lipatov <lav@etersoft.ru>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
@@ -33,10 +33,19 @@ case $PMTYPE in
 		;;
 	yum-rpm)
 		docmd yum check
-		docmd package-cleanup --leaves
-		sudocmd yum remove $(package-cleanup --leaves)
+		docmd package-cleanup --problems
+
 		#docmd package-cleanup --dupes
 		sudocmd package-cleanup --cleandupes
+
+		# cleanup orphanes?
+		while true ; do
+			docmd package-cleanup --leaves
+			# FIXME: package-cleanup have to use stderr for errors
+			local PKGLIST=$(package-cleanup --leaves | grep -v "Loaded plugins" | grep -v "Unable to")
+			[ -n "$PKGLIST" ] || break
+			sudocmd yum remove $PKGLIST
+		done
 		;;
 	urpm-rpm)
 		sudocmd urpme --auto-orphans
