fix messages

diff --git a/bin/epm-assure b/bin/epm-assure
--- a/bin/epm-assure
+++ b/bin/epm-assure
@@ -43,7 +43,7 @@ __epm_assure()
     fi
 
     # TODO: use package name normalization
-    info "Install appropriate package for $1 command..."
+    info "Installing appropriate package for $1 command..."
 
     local PACKAGE="$2"
     [ -n "$PACKAGE" ] || PACKAGE="$1"
@@ -58,7 +58,7 @@ __epm_assure()
 
 epm_assure()
 {
-    [ -n "$pkg_filenames" ] || fatal "Run assure without params"
+    [ -n "$pkg_filenames" ] || fatal "Assure: Missing params. Check $0 --help for info."
 
     # use helper func for extract separate params
     __epm_assure $pkg_filenames
diff --git a/bin/epm-requires b/bin/epm-requires
--- a/bin/epm-requires
+++ b/bin/epm-requires
@@ -23,7 +23,9 @@ epm_requires_files()
 {
 	[ -n "$pkg_files" ] || return
 
-	case $(get_package_type $pkg_files) in
+	local PKGTYPE="$(case $(get_package_type $pkg_files))"
+
+	case "$PKGTYPE" in
 		rpm)
 			docmd rpm -q --requires -p $pkg_files
 			;;
@@ -31,7 +33,7 @@ epm_requires_files()
 			a= docmd dpkg -I $pkg_files | grep "^ *Depends:" | sed "s|^ *Depends:||g"
 			;;
 		*)
-			fatal "Have no suitable command for $PMTYPE"
+			fatal "Have no suitable command for $PKGTYPE"
 			;;
 	esac
 }
@@ -92,7 +94,7 @@ docmd $CMD $pkg_names
 
 epm_requires()
 {
-	[ -n "$pkg_filenames" ] || fatal "Run query without names"
+	[ -n "$pkg_filenames" ] || fatal "Requires: missing package(s) name"
 	epm_requires_files
 	epm_requires_names
 }
diff --git a/bin/epm-search_file b/bin/epm-search_file
--- a/bin/epm-search_file
+++ b/bin/epm-search_file
@@ -21,10 +21,12 @@
 # https://bugzilla.altlinux.org/show_bug.cgi?id=14449
 local_content_search()
 {
+    # TODO: use global get_sysarch function
     local SYSARCH
     SYSARCH=$(uname -m)
     [ "$SYSARCH" = "x86_64" ] || SYSARCH=i586
 
+    # FIXME: use config or/and web url
     local REPODIR=/var/ftp/pub/ALTLinux/Sisyphus
     local CI=$REPODIR/$SYSARCH/base/contents_index
     local CINOA=$REPODIR/noarch/base/contents_index
@@ -43,7 +45,7 @@ local_content_search()
 epm_search_file()
 {
 	local CMD
-	[ -n "$pkg_filenames" ] || fatal "Run search without names"
+	[ -n "$pkg_filenames" ] || fatal "Search file: missing file name(s)"
 
 case $PMTYPE in
 	apt-rpm)
