small fixes
Signed-off-by: Vitaly Lipatov <lav@etersoft.ru>

diff --git a/bin/epm-sh-functions b/bin/epm-sh-functions
--- a/bin/epm-sh-functions
+++ b/bin/epm-sh-functions
@@ -60,7 +60,7 @@ strip_spaces()
 fatal()
 {
 	if [ -z "$TEXTDOMAIN" ] ; then
-		echo "Error in $0: $@" >&2
+		echo "Error: $@" >&2
 #	else
 #		echog "Error in $0: $@" >&2
 	fi
