serv: replace tab with 4 spaces

diff --git a/bin/serv-cat b/bin/serv-cat
--- a/bin/serv-cat
+++ b/bin/serv-cat
@@ -19,23 +19,23 @@
 
 serv_cat()
 {
-	local SERVICE="$1"
-	shift
+    local SERVICE="$1"
+    shift
 
-	case $SERVICETYPE in
-		systemd)
-			docmd systemctl cat "$SERVICE" "$@"
-			;;
-		*)
-			case $BASEDISTRNAME in
-			"alt")
-				local INITFILE=/etc/init.d/$SERVICE
-				[ -r "$INITFILE" ] || fatal "Can't find init file $INITFILE"
-				docmd cat $INITFILE
-				return ;;
-			*)
-				fatal "Have no suitable for $DISTRNAME command for $SERVICETYPE"
-				;;
-			esac
-	esac
+    case $SERVICETYPE in
+        systemd)
+            docmd systemctl cat "$SERVICE" "$@"
+            ;;
+        *)
+            case $BASEDISTRNAME in
+            "alt")
+                local INITFILE=/etc/init.d/$SERVICE
+                [ -r "$INITFILE" ] || fatal "Can't find init file $INITFILE"
+                docmd cat $INITFILE
+                return ;;
+            *)
+                fatal "Have no suitable for $DISTRNAME command for $SERVICETYPE"
+                ;;
+            esac
+    esac
 }
diff --git a/bin/serv-enable b/bin/serv-enable
--- a/bin/serv-enable
+++ b/bin/serv-enable
@@ -23,39 +23,39 @@ load_helper serv-status
 # Enable service by default
 serv_enable()
 {
-	local SERVICE="$1"
+    local SERVICE="$1"
 
-	is_service_autostart $1 && info "Service $1 is already enabled for startup" && return
+    is_service_autostart $1 && info "Service $1 is already enabled for startup" && return
 
-	case $SERVICETYPE in
-		service-chkconfig)
-			if is_anyservice $SERVICE ; then
-				sudocmd anyservice $SERVICE on
-				return
-			fi
-			sudocmd chkconfig --add $1 || return
-			sudocmd chkconfig $1 on
-			;;
-		service-upstart)
-			sudocmd chkconfig --add $1 || return
-			sudocmd chkconfig $1 on
-			;;
-		service-initd|service-update)
-			sudocmd update-rc.d $1 defaults
-			;;
-		systemd)
-			sudocmd systemctl enable $1
-			;;
-		openrc)
-			sudocmd rc-update add $1 default
-			;;
-		runit)
-			assure_exists $SERVICE
-			[ -r "/etc/sv/$SERVICE" ] || fatal "Can't find /etc/sv/$SERVICE"
-			sudocmd ln -s /etc/sv/$SERVICE /var/service/
-			;;
-		*)
-			fatal "Have no suitable command for $SERVICETYPE"
-			;;
-	esac
+    case $SERVICETYPE in
+        service-chkconfig)
+            if is_anyservice $SERVICE ; then
+                sudocmd anyservice $SERVICE on
+                return
+            fi
+            sudocmd chkconfig --add $1 || return
+            sudocmd chkconfig $1 on
+            ;;
+        service-upstart)
+            sudocmd chkconfig --add $1 || return
+            sudocmd chkconfig $1 on
+            ;;
+        service-initd|service-update)
+            sudocmd update-rc.d $1 defaults
+            ;;
+        systemd)
+            sudocmd systemctl enable $1
+            ;;
+        openrc)
+            sudocmd rc-update add $1 default
+            ;;
+        runit)
+            assure_exists $SERVICE
+            [ -r "/etc/sv/$SERVICE" ] || fatal "Can't find /etc/sv/$SERVICE"
+            sudocmd ln -s /etc/sv/$SERVICE /var/service/
+            ;;
+        *)
+            fatal "Have no suitable command for $SERVICETYPE"
+            ;;
+    esac
 }
